// Code generated by mygo; DO NOT EDIT.

package json

import (
	"fmt"
	"strconv"
	"strings"

	ps "github.com/mygo-lang/mygo/lib/text/parsec"
	. "github.com/mygo-lang/mygo/prelude"
)

type JsonValue interface {
	isJsonValue()
}
type JsonValueJNull struct {
}

func (_ JsonValueJNull) isJsonValue() {
}
func JsonValueJNullCtor() JsonValue {
	return JsonValueJNull{}
}

type JsonValueJBool struct {
	F0 bool
}

func (_ JsonValueJBool) isJsonValue() {
}
func JsonValueJBoolCtor(a0 bool) JsonValue {
	return JsonValueJBool{F0: a0}
}

type JsonValueJNumber struct {
	F0 float64
}

func (_ JsonValueJNumber) isJsonValue() {
}
func JsonValueJNumberCtor(a0 float64) JsonValue {
	return JsonValueJNumber{F0: a0}
}

type JsonValueJString struct {
	F0 string
}

func (_ JsonValueJString) isJsonValue() {
}
func JsonValueJStringCtor(a0 string) JsonValue {
	return JsonValueJString{F0: a0}
}

type JsonValueJArray struct {
	F0 []JsonValue
}

func (_ JsonValueJArray) isJsonValue() {
}
func JsonValueJArrayCtor(a0 []JsonValue) JsonValue {
	return JsonValueJArray{F0: a0}
}

type JsonValueJObject struct {
	F0 []struct {
		F0 string
		F1 JsonValue
	}
}

func (_ JsonValueJObject) isJsonValue() {
}
func JsonValueJObjectCtor(a0 []struct {
	F0 string
	F1 JsonValue
}) JsonValue {
	return JsonValueJObject{F0: a0}
}
func MygoIT8ToStringFN17JsonValueToStringGN9JsonValueEM8ToString(value JsonValue) string {
	return func() string {
		if _, ok := value.(JsonValueJNull); ok {
			return func() string {
				return "null"
			}()
		} else {
			if v_5, ok := value.(JsonValueJBool); ok {
				return func() string {
					return func() string {
						if v_5.F0 {
							return "true"
						} else {
							return "false"
						}
					}()
				}()
			} else {
				if v_4, ok := value.(JsonValueJNumber); ok {
					return func() string {
						return MygoIT8ToStringFN17JsonValueToStringGN9JsonValueEM8ToString(v_4.F0)
					}()
				} else {
					if v_3, ok := value.(JsonValueJString); ok {
						return func() string {
							return "\"" + jsonEscape(v_3.F0) + "\""
						}()
					} else {
						if v_2, ok := value.(JsonValueJArray); ok {
							return func() string {
								parts_5 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(v_2.F0, func(v JsonValue) string {
									return MygoIT8ToStringFN17JsonValueToStringGN9JsonValueEM8ToString(v)
								})
								return "[" + strings.Join(parts_5, ",") + "]"
							}()
						} else {
							if v_1, ok := value.(JsonValueJObject); ok {
								return func() string {
									parts_4 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(v_1.F0, func(p struct {
										F0 string
										F1 JsonValue
									}) string {
										__tuple_1 := p
										k_2 := __tuple_1.F0
										v_3 := __tuple_1.F1
										return "\"" + jsonEscape(k_2) + "\":" + MygoIT8ToStringFN17JsonValueToStringGN9JsonValueEM8ToString(JsonValue(v_3))
									})
									return "{" + strings.Join(parts_4, ",") + "}"
								}()
							} else {
								panic("unreachable")
							}
						}
					}
				}
			}
		}
	}()
}
func jsonEscape(s string) string {
	parts_14 := MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM4Fold(s, []string([]string{}), func(acc []string, r rune) []string {
		escaped_13 := func() string {
			if r == '"' {
				return func() string {
					return "\\\""
				}()
			} else {
				if r == '\\' {
					return func() string {
						return "\\\\\\\\"
					}()
				} else {
					if r == '\b' {
						return func() string {
							return "\\b"
						}()
					} else {
						if r == '\f' {
							return func() string {
								return "\\f"
							}()
						} else {
							if r == '\n' {
								return func() string {
									return "\\n"
								}()
							} else {
								if r == '\r' {
									return func() string {
										return "\\r"
									}()
								} else {
									if r == '\t' {
										return func() string {
											return "\\t"
										}()
									} else {
										return func() string {
											return func() string {
												if r < ' ' {
													return func() string {
														v_6 := int(r)
														var hexChars_7 []rune = []rune{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'}
														d0_8 := v_6 / 4096
														d1_9 := (v_6 - d0_8*4096) / 256
														d2_10 := (v_6 - d0_8*4096 - d1_9*256) / 16
														d3_11 := v_6 - d0_8*4096 - d1_9*256 - d2_10*16
														escapedRunes_12 := []rune{MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(hexChars_7, d0_8), '\x00'), MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(hexChars_7, d1_9), '\x00'), MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(hexChars_7, d2_10), '\x00'), MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(hexChars_7, d3_11), '\x00')}
														return "\\\\u" + MygoIN6StringM9FromRunes(escapedRunes_12)
													}()
												} else {
													return MygoIN6StringM9FromRunes([]rune{r})
												}
											}()
										}()
									}
								}
							}
						}
					}
				}
			}
		}()
		return MygoIN5SliceM6Append(acc, escaped_13)
	})
	return strings.Join(parts_14, "")
}
func ws[A any](p ps.Parser[A]) ps.Parser[A] {
	sp_15 := ps.PMany(ps.PSatisfy(func(r rune) bool {
		return r == ' ' || r == '\t' || r == '\n' || r == '\r'
	}, "whitespace"))
	return ps.PBetween(sp_15, p, sp_15)
}
func pNull() ps.Parser[JsonValue] {
	return ps.PMap(ps.PString("null"), func(_ string) JsonValue {
		return JsonValueJNullCtor()
	})
}
func pBool() ps.Parser[JsonValue] {
	return ps.POrElse(ps.PMap(ps.PString("true"), func(_ string) JsonValue {
		return JsonValueJBoolCtor(true)
	}), ps.PMap(ps.PString("false"), func(_ string) JsonValue {
		return JsonValueJBoolCtor(false)
	}))
}
func pNumber() ps.Parser[JsonValue] {
	return ps.Parser[JsonValue]{Run: func(state ps.State) ps.Reply[JsonValue] {
		r1_16 := ps.PeekRune(state)
		if !r1_16.Ok {
			return ps.Reply[JsonValue]{Ok: false, Consumed: false, Value: Zero[JsonValue](), State: state, Error: ps.ErrorAt(state.Position, "number", ps.EmptyExpected())}
		}
		curState_17 := state
		var runes_18 []rune = []rune{}
		rSign_19 := ps.PeekRune(curState_17)
		if rSign_19.Ok && rSign_19.Value == '-' {
			runes_18 = MygoIN5SliceM6Append(runes_18, '-')
			curState_17 = ps.AdvanceRune(curState_17)
		}
		rFirst_20 := ps.PeekRune(curState_17)
		if !rFirst_20.Ok || rFirst_20.Value < '0' || rFirst_20.Value > '9' {
			return ps.Reply[JsonValue]{Ok: false, Consumed: false, Value: Zero[JsonValue](), State: state, Error: ps.ErrorAt(state.Position, "number", ps.EmptyExpected())}
		}
		func() {
			for true {
				rn := ps.PeekRune(curState_17)
				if !rn.Ok {
					break
				} else {
				}
				if rn.Value < '0' || rn.Value > '9' {
					break
				} else {
				}
				runes_18 = MygoIN5SliceM6Append(runes_18, rn.Value)
				curState_17 = ps.AdvanceRune(curState_17)
			}
		}()
		rDot_21 := ps.PeekRune(curState_17)
		if rDot_21.Ok && rDot_21.Value == '.' {
			runes_18 = MygoIN5SliceM6Append(runes_18, '.')
			curState_17 = ps.AdvanceRune(curState_17)
			rFrac_22 := ps.PeekRune(curState_17)
			if !rFrac_22.Ok || rFrac_22.Value < '0' || rFrac_22.Value > '9' {
				return ps.Reply[JsonValue]{Ok: false, Consumed: false, Value: Zero[JsonValue](), State: state, Error: ps.ErrorAt(state.Position, "number", ps.EmptyExpected())}
			}
			func() {
				for true {
					rn := ps.PeekRune(curState_17)
					if !rn.Ok {
						break
					} else {
					}
					if rn.Value < '0' || rn.Value > '9' {
						break
					} else {
					}
					runes_18 = MygoIN5SliceM6Append(runes_18, rn.Value)
					curState_17 = ps.AdvanceRune(curState_17)
				}
			}()
		}
		rExp_23 := ps.PeekRune(curState_17)
		if rExp_23.Ok && (rExp_23.Value == 'e' || rExp_23.Value == 'E') {
			runes_18 = MygoIN5SliceM6Append(runes_18, rExp_23.Value)
			curState_17 = ps.AdvanceRune(curState_17)
			rSign2_24 := ps.PeekRune(curState_17)
			if rSign2_24.Ok && (rSign2_24.Value == '+' || rSign2_24.Value == '-') {
				runes_18 = MygoIN5SliceM6Append(runes_18, rSign2_24.Value)
				curState_17 = ps.AdvanceRune(curState_17)
			}
			rExpDig_25 := ps.PeekRune(curState_17)
			if !rExpDig_25.Ok || rExpDig_25.Value < '0' || rExpDig_25.Value > '9' {
				return ps.Reply[JsonValue]{Ok: false, Consumed: false, Value: Zero[JsonValue](), State: state, Error: ps.ErrorAt(state.Position, "number", ps.EmptyExpected())}
			}
			func() {
				for true {
					rn := ps.PeekRune(curState_17)
					if !rn.Ok {
						break
					} else {
					}
					if rn.Value < '0' || rn.Value > '9' {
						break
					} else {
					}
					runes_18 = MygoIN5SliceM6Append(runes_18, rn.Value)
					curState_17 = ps.AdvanceRune(curState_17)
				}
			}()
		}
		numStr_26 := MygoIN6StringM9FromRunes(runes_18)
		return func() ps.Reply[JsonValue] {
			if v_8, ok := func() Result[float64, error] {
				__mygo_result_val, __mygo_result_err := strconv.ParseFloat(numStr_26, 64)
				if __mygo_result_err != nil {
					return Err[float64, error](__mygo_result_err)
				}
				return Ok[float64, error](__mygo_result_val)
			}().(ResultOk[float64, error]); ok {
				return func() ps.Reply[JsonValue] {
					return ps.Reply[JsonValue]{Ok: true, Consumed: true, Value: JsonValueJNumberCtor(v_8.F0), State: curState_17, Error: ps.EmptyError(curState_17.Position)}
				}()
			} else {
				if v_7, ok := func() Result[float64, error] {
					__mygo_result_val, __mygo_result_err := strconv.ParseFloat(numStr_26, 64)
					if __mygo_result_err != nil {
						return Err[float64, error](__mygo_result_err)
					}
					return Ok[float64, error](__mygo_result_val)
				}().(ResultErr[float64, error]); ok {
					return func() ps.Reply[JsonValue] {
						return ps.Reply[JsonValue]{Ok: false, Consumed: true, Value: Zero[JsonValue](), State: curState_17, Error: ps.ErrorAt(state.Position, v_7.F0.Error(), ps.EmptyExpected())}
					}()
				} else {
					panic("unreachable")
				}
			}
		}()
	}}
}
func pString() ps.Parser[JsonValue] {
	pEscape_30 := func() ps.Parser[rune] {
		pHexDigit_27 := ps.PSatisfy(func(r rune) bool {
			return r >= '0' && r <= '9' || r >= 'a' && r <= 'f' || r >= 'A' && r <= 'F'
		}, "hex digit")
		return ps.PBind(ps.PChar('\\'), func(_ rune) ps.Parser[rune] {
			return ps.PChoice([]ps.Parser[rune]{ps.PMap(ps.PChar('"'), func(_ rune) rune {
				return '"'
			}), ps.PMap(ps.PChar('\\'), func(_ rune) rune {
				return '\\'
			}), ps.PMap(ps.PChar('/'), func(_ rune) rune {
				return '/'
			}), ps.PMap(ps.PChar('b'), func(_ rune) rune {
				return '\b'
			}), ps.PMap(ps.PChar('f'), func(_ rune) rune {
				return '\f'
			}), ps.PMap(ps.PChar('n'), func(_ rune) rune {
				return '\n'
			}), ps.PMap(ps.PChar('r'), func(_ rune) rune {
				return '\r'
			}), ps.PMap(ps.PChar('t'), func(_ rune) rune {
				return '\t'
			}), ps.PBind(ps.PChar('u'), func(_ rune) ps.Parser[rune] {
				return ps.PBind(pHexDigit_27, func(d0 rune) ps.Parser[rune] {
					return ps.PBind(pHexDigit_27, func(d1 rune) ps.Parser[rune] {
						return ps.PBind(pHexDigit_27, func(d2 rune) ps.Parser[rune] {
							return ps.PMap(pHexDigit_27, func(d3 rune) rune {
								hexStr_28 := MygoIN6StringM9FromRunes([]rune{d0, d1, d2, d3})
								result_29 := func() Result[int64, error] {
									__mygo_result_val, __mygo_result_err := strconv.ParseInt(hexStr_28, 16, 32)
									if __mygo_result_err != nil {
										return Err[int64, error](__mygo_result_err)
									}
									return Ok[int64, error](__mygo_result_val)
								}()
								return func() rune {
									if v_9, ok := result_29.(ResultOk[int64, error]); ok {
										return func() rune {
											return rune(v_9.F0)
										}()
									} else {
										return func() rune {
											return rune(0)
										}()
									}
								}()
							})
						})
					})
				})
			})})
		})
	}
	pCharContent_31 := func() ps.Parser[rune] {
		return ps.POrElse(pEscape_30(), ps.PSatisfy(func(r rune) bool {
			return r != '"' && r != '\\'
		}, "string character"))
	}
	return ps.PBind(ps.PChar('"'), func(_ rune) ps.Parser[JsonValue] {
		return ps.PBind(ps.PMany(pCharContent_31()), func(chars []rune) ps.Parser[JsonValue] {
			return ps.PMap(ps.PChar('"'), func(_ rune) JsonValue {
				return JsonValueJStringCtor(MygoIN6StringM9FromRunes(chars))
			})
		})
	})
}
func ParseJson(input string) Result[JsonValue, string] {
	nullP_32 := pNull()
	boolP_33 := pBool()
	numP_34 := pNumber()
	strP_35 := pString()
	var valueP_36 ps.Parser[JsonValue]
	var arrP_37 ps.Parser[JsonValue]
	var pairP_38 ps.Parser[struct {
		F0 string
		F1 JsonValue
	}]
	var objP_39 ps.Parser[JsonValue]
	valueP_36 = ps.Parser[JsonValue]{Run: func(state ps.State) ps.Reply[JsonValue] {
		return ws(ps.PChoice([]ps.Parser[JsonValue]{nullP_32, boolP_33, numP_34, strP_35, arrP_37, objP_39})).Run(state)
	}}
	arrP_37 = ps.PMap(ps.PBetween(ws(ps.PChar('[')), ps.PSepBy(valueP_36, ws(ps.PChar(','))), ws(ps.PChar(']'))), func(items []JsonValue) JsonValue {
		return JsonValueJArrayCtor(items)
	})
	pairP_38 = ps.Parser[struct {
		F0 string
		F1 JsonValue
	}]{Run: func(s ps.State) ps.Reply[struct {
		F0 string
		F1 JsonValue
	}] {
		kr_40 := ws(pString()).Run(s)
		if !kr_40.Ok {
			return ps.Reply[struct {
				F0 string
				F1 JsonValue
			}]{Ok: kr_40.Ok, Consumed: kr_40.Consumed, State: kr_40.State, Error: kr_40.Error, Value: struct {
				F0 string
				F1 JsonValue
			}{F0: "", F1: JsonValueJNullCtor()}}
		}
		keyStr_41 := func() string {
			if v_10, ok := kr_40.Value.(JsonValueJString); ok {
				return func() string {
					return string(v_10.F0)
				}()
			} else {
				return func() string {
					return ""
				}()
			}
		}()
		cr_42 := ws(ps.PChar(':')).Run(kr_40.State)
		if !cr_42.Ok {
			return ps.Reply[struct {
				F0 string
				F1 JsonValue
			}]{Ok: cr_42.Ok, Consumed: cr_42.Consumed, State: cr_42.State, Error: cr_42.Error, Value: struct {
				F0 string
				F1 JsonValue
			}{F0: "", F1: JsonValueJNullCtor()}}
		}
		vr_43 := valueP_36.Run(cr_42.State)
		if !vr_43.Ok {
			return ps.Reply[struct {
				F0 string
				F1 JsonValue
			}]{Ok: vr_43.Ok, Consumed: vr_43.Consumed, State: vr_43.State, Error: vr_43.Error, Value: struct {
				F0 string
				F1 JsonValue
			}{F0: "", F1: JsonValueJNullCtor()}}
		}
		return ps.Reply[struct {
			F0 string
			F1 JsonValue
		}]{Ok: true, Consumed: true, Value: struct {
			F0 string
			F1 JsonValue
		}{F0: keyStr_41, F1: vr_43.Value}, State: vr_43.State, Error: ps.EmptyError(vr_43.State.Position)}
	}}
	objP_39 = ps.PMap(ps.PBetween(ws(ps.PChar('{')), ps.PSepBy(pairP_38, ws(ps.PChar(','))), ws(ps.PChar('}'))), func(pairs []struct {
		F0 string
		F1 JsonValue
	}) JsonValue {
		return JsonValueJObjectCtor(pairs)
	})
	r_44 := ps.ParseInput(valueP_36, input)
	return func() Result[JsonValue, string] {
		if !r_44.Ok {
			return func() Result[JsonValue, string] {
				if v_12, ok := r_44.Error.(OptionSome[ps.ParseError]); ok {
					return func() Result[JsonValue, string] {
						errMsg_45 := fmt.Sprintf("parse error at line %d, column %d: %s", v_12.F0.Position.Line, v_12.F0.Position.Column, v_12.F0.Message)
						return Err[JsonValue, string](errMsg_45)
					}()
				} else {
					if _, ok := r_44.Error.(OptionNone[ps.ParseError]); ok {
						return func() Result[JsonValue, string] {
							return Err[JsonValue, string]("parse error")
						}()
					} else {
						panic("unreachable")
					}
				}
			}()
		} else {
			return Ok[JsonValue, string](r_44.Value)
		}
	}()
}
