// Code generated by mygo; DO NOT EDIT.

package codegen2

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strconv"
	"strings"

	"github.com/mygo-lang/mygo/internal/mygo/ast2"
	"github.com/mygo-lang/mygo/internal/mygo/parser2"
	. "github.com/mygo-lang/mygo/prelude"
)

func funcSignature(prefix string, tps []string, params []ast2.Param, ret Option[ast2.TypeExpr], outer map[string]struct{}) string {
	var allTypes_58 map[string]struct{} = outer
	allTypes_58 = MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(tps, allTypes_58, func(acc map[string]struct{}, tp string) map[string]struct{} {
		return MygoIN3SetM3Add(acc, tp)
	})
	ps_59 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(params, func(p ast2.Param) string {
		return sanitizeIdent(p.Name) + " " + goType(p.Type, allTypes_58)
	})
	return prefix + typeParamDecl(tps) + "(" + joinStrings(ps_59, ", ") + ")" + returnTypeString(ret, allTypes_58)
}
func returnTypeString(ret Option[ast2.TypeExpr], tps map[string]struct{}) string {
	return func() string {
		if v_32, ok := ret.(OptionSome[ast2.TypeExpr]); ok {
			return func() string {
				r_60 := goReturnType(v_32.F0, tps)
				return func() string {
					if r_60 == "" {
						return ""
					} else {
						return " " + r_60
					}
				}()
			}()
		} else {
			if _, ok := ret.(OptionNone[ast2.TypeExpr]); ok {
				return func() string {
					return ""
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func typeParamDecl(tps []string) string {
	return func() string {
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(tps) == 0 {
			return ""
		} else {
			return func() string {
				parts_61 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(tps, func(tp string) string {
					return sanitizeIdent(tp) + " any"
				})
				return "[" + joinStrings(parts_61, ", ") + "]"
			}()
		}
	}()
}
func typeParamUse(tps []string) string {
	return func() string {
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(tps) == 0 {
			return ""
		} else {
			return func() string {
				parts_62 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(tps, func(tp string) string {
					return sanitizeIdent(tp)
				})
				return "[" + joinStrings(parts_62, ", ") + "]"
			}()
		}
	}()
}
func sourceToGenName(path string) string {
	parts_63 := strings.Split(path, "/")
	var base_64 string = MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(parts_63, MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(parts_63)-1), path)
	base_64 = strings.TrimSuffix(base_64, ".mygo")
	if base_64 == "" {
		base_64 = "mygo"
	}
	if strings.HasSuffix(base_64, "_test") {
		return "zz_" + strings.TrimSuffix(base_64, "_test") + ".gen_test.go"
	}
	return "zz_" + base_64 + ".gen.go"
}
func renderGoFile(parts GoFileParts) Result[string, string] {
	return func() Result[string, string] {
		f := &ast.File{Name: ast.NewIdent(parts.PackageName)}
		for _, im := range parts.Imports {
			spec := &ast.ImportSpec{Path: &ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(im.Path)}}
			if im.Alias != "" && im.Alias != importAliasForPath(im.Path) {
				spec.Name = ast.NewIdent(im.Alias)
			}
			f.Decls = append(f.Decls, &ast.GenDecl{Tok: token.IMPORT, Specs: append([]ast.Spec(nil), spec)})
		}
		for _, src := range parts.Decls {
			declSrc := "package p\n" + src
			parsed, err := parser.ParseFile(token.NewFileSet(), "decl.go", declSrc, parser.ParseComments)
			if err != nil {
				return Err[string, string]("go/ast parse decl: " + err.Error() + "\n" + src)
			}
			f.Decls = append(f.Decls, parsed.Decls...)
		}
		var buf bytes.Buffer
		if err := format.Node(&buf, token.NewFileSet(), f); err != nil {
			return Err[string, string]("go/format: " + err.Error())
		}
		return Ok[string, string](buf.String())
	}()
}
func parseSourceAsAst2(input string) Result[ast2.File, string] {
	return func() Result[ast2.File, string] {
		if v_34, ok := parser2.ParseFile(input).(ResultOk[parser2.File, string]); ok {
			return func() Result[ast2.File, string] {
				return Ok[ast2.File, string](convertFile(v_34.F0))
			}()
		} else {
			if v_33, ok := parser2.ParseFile(input).(ResultErr[parser2.File, string]); ok {
				return func() Result[ast2.File, string] {
					return Err[ast2.File, string](v_33.F0)
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func convertFile(file parser2.File) ast2.File {
	return ast2.File{PackageName: file.PackageName, Decls: convertDecls(file.Decls)}
}
func convertType(t parser2.TypeExpr) ast2.TypeExpr {
	return func() ast2.TypeExpr {
		if v_39, ok := t.(parser2.TypeExprNamedType); ok {
			return func() ast2.TypeExpr {
				return ast2.TypeExprNamedTypeCtor(v_39.F0, convertTypes(v_39.F1))
			}()
		} else {
			if v_38, ok := t.(parser2.TypeExprFuncType); ok {
				return func() ast2.TypeExpr {
					r_66 := convertType(*v_38.F1)
					return ast2.TypeExprFuncTypeCtor(convertTypes(v_38.F0), &r_66)
				}()
			} else {
				if v_37, ok := t.(parser2.TypeExprTupleType); ok {
					return func() ast2.TypeExpr {
						return ast2.TypeExprTupleTypeCtor(convertTypes(v_37.F0))
					}()
				} else {
					if _, ok := t.(parser2.TypeExprUnitType); ok {
						return func() ast2.TypeExpr {
							return ast2.TypeExprUnitTypeCtor()
						}()
					} else {
						if v_35, ok := t.(parser2.TypeExprInlineGo); ok {
							return func() ast2.TypeExpr {
								bt_65 := convertType(*v_35.F0)
								return ast2.TypeExprInlineGoCtor(&bt_65, v_35.F1)
							}()
						} else {
							panic("unreachable")
						}
					}
				}
			}
		}
	}()
}
func convertDecls(items []parser2.Decl) []ast2.Decl {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(d parser2.Decl) ast2.Decl {
		return convertDecl(d)
	})
}
func convertDecl(d parser2.Decl) ast2.Decl {
	return func() ast2.Decl {
		if v_45, ok := d.(parser2.DeclImportDecl); ok {
			return func() ast2.Decl {
				return ast2.DeclImportDeclCtor(v_45.F0, v_45.F1)
			}()
		} else {
			if v_44, ok := d.(parser2.DeclFuncDecl); ok {
				return func() ast2.Decl {
					return ast2.DeclFuncDeclCtor(v_44.F0, v_44.F1, convertParams(v_44.F2), convertTypeOption(v_44.F3), convertExpr(v_44.F4))
				}()
			} else {
				if v_43, ok := d.(parser2.DeclStructDecl); ok {
					return func() ast2.Decl {
						return ast2.DeclStructDeclCtor(v_43.F0, v_43.F1, convertFields(v_43.F2))
					}()
				} else {
					if v_42, ok := d.(parser2.DeclEnumDecl); ok {
						return func() ast2.Decl {
							return ast2.DeclEnumDeclCtor(v_42.F0, v_42.F1, convertVariants(v_42.F2))
						}()
					} else {
						if v_41, ok := d.(parser2.DeclInterfaceDecl); ok {
							return func() ast2.Decl {
								return ast2.DeclInterfaceDeclCtor(v_41.F0, v_41.F1, convertFuncSigs(v_41.F2))
							}()
						} else {
							if v_40, ok := d.(parser2.DeclImplDecl); ok {
								return func() ast2.Decl {
									return ast2.DeclImplDeclCtor(v_40.F0, convertType(v_40.F1), convertTypeOption(v_40.F2), convertImplMethods(v_40.F3))
								}()
							} else {
								panic("unreachable")
							}
						}
					}
				}
			}
		}
	}()
}
func convertTypes(items []parser2.TypeExpr) []ast2.TypeExpr {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(t parser2.TypeExpr) ast2.TypeExpr {
		return convertType(t)
	})
}
func convertTypeOption(item Option[parser2.TypeExpr]) Option[ast2.TypeExpr] {
	return func() Option[ast2.TypeExpr] {
		if v_47, ok := item.(OptionSome[parser2.TypeExpr]); ok {
			return func() Option[ast2.TypeExpr] {
				return Some[ast2.TypeExpr](convertType(v_47.F0))
			}()
		} else {
			if _, ok := item.(OptionNone[parser2.TypeExpr]); ok {
				return func() Option[ast2.TypeExpr] {
					return None[ast2.TypeExpr]()
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func convertStmt(s parser2.Stmt) ast2.Stmt {
	return func() ast2.Stmt {
		if v_54, ok := s.(parser2.StmtExprStmt); ok {
			return func() ast2.Stmt {
				return ast2.StmtExprStmtCtor(convertExpr(v_54.F0))
			}()
		} else {
			if v_53, ok := s.(parser2.StmtLetStmt); ok {
				return func() ast2.Stmt {
					return ast2.StmtLetStmtCtor(ast2.Bind{Name: v_53.F0.Name, Type: convertTypeOption(v_53.F0.Type), Value: convertExpr(v_53.F0.Value)})
				}()
			} else {
				if v_52, ok := s.(parser2.StmtVarStmt); ok {
					return func() ast2.Stmt {
						return ast2.StmtVarStmtCtor(ast2.Bind{Name: v_52.F0.Name, Type: convertTypeOption(v_52.F0.Type), Value: convertExpr(v_52.F0.Value)})
					}()
				} else {
					if v_51, ok := s.(parser2.StmtWhileStmt); ok {
						return func() ast2.Stmt {
							c_69 := convertExpr(v_51.F0)
							b_70 := convertExpr(v_51.F1)
							return ast2.StmtWhileStmtCtor(c_69, b_70)
						}()
					} else {
						if v_50, ok := s.(parser2.StmtAssignStmt); ok {
							return func() ast2.Stmt {
								t_67 := convertExpr(v_50.F0)
								v_68 := convertExpr(v_50.F1)
								return ast2.StmtAssignStmtCtor(t_67, v_68)
							}()
						} else {
							if _, ok := s.(parser2.StmtReturnStmt); ok {
								return func() ast2.Stmt {
									return ast2.StmtReturnStmtCtor()
								}()
							} else {
								if v_48, ok := s.(parser2.StmtReturnWithStmt); ok {
									return func() ast2.Stmt {
										return ast2.StmtReturnWithStmtCtor(convertExpr(v_48.F0))
									}()
								} else {
									panic("unreachable")
								}
							}
						}
					}
				}
			}
		}
	}()
}
func convertExpr(e parser2.Expr) ast2.Expr {
	return func() ast2.Expr {
		if v_67, ok := e.(parser2.ExprIdentExpr); ok {
			return func() ast2.Expr {
				return ast2.ExprIdentExprCtor(v_67.F0)
			}()
		} else {
			if v_66, ok := e.(parser2.ExprNumberExpr); ok {
				return func() ast2.Expr {
					return ast2.ExprNumberExprCtor(v_66.F0)
				}()
			} else {
				if v_65, ok := e.(parser2.ExprStringExpr); ok {
					return func() ast2.Expr {
						return ast2.ExprStringExprCtor(v_65.F0)
					}()
				} else {
					if v_64, ok := e.(parser2.ExprBoolExpr); ok {
						return func() ast2.Expr {
							return ast2.ExprBoolExprCtor(v_64.F0)
						}()
					} else {
						if _, ok := e.(parser2.ExprUnitExpr); ok {
							return func() ast2.Expr {
								return ast2.ExprUnitExprCtor()
							}()
						} else {
							if v_62, ok := e.(parser2.ExprCallExpr); ok {
								return func() ast2.Expr {
									c_79 := convertExpr(*v_62.F0)
									return ast2.ExprCallExprCtor(&c_79, convertExprs(v_62.F1))
								}()
							} else {
								if v_61, ok := e.(parser2.ExprFieldExpr); ok {
									return func() ast2.Expr {
										b_78 := convertExpr(*v_61.F0)
										return ast2.ExprFieldExprCtor(&b_78, v_61.F1)
									}()
								} else {
									if v_60, ok := e.(parser2.ExprUnaryExpr); ok {
										return func() ast2.Expr {
											v_77 := convertExpr(*v_60.F1)
											return ast2.ExprUnaryExprCtor(v_60.F0, &v_77)
										}()
									} else {
										if v_59, ok := e.(parser2.ExprBinaryExpr); ok {
											return func() ast2.Expr {
												l_75 := convertExpr(*v_59.F1)
												r_76 := convertExpr(*v_59.F2)
												return ast2.ExprBinaryExprCtor(v_59.F0, &l_75, &r_76)
											}()
										} else {
											if v_58, ok := e.(parser2.ExprIfExpr); ok {
												return func() ast2.Expr {
													c_72 := convertExpr(*v_58.F0)
													t_73 := convertExpr(*v_58.F1)
													e2_74 := convertExpr(*v_58.F2)
													return ast2.ExprIfExprCtor(&c_72, &t_73, &e2_74)
												}()
											} else {
												if v_57, ok := e.(parser2.ExprBlockExpr); ok {
													return func() ast2.Expr {
														return ast2.ExprBlockExprCtor(convertStmts(v_57.F0))
													}()
												} else {
													if v_56, ok := e.(parser2.ExprStructLitExpr); ok {
														return func() ast2.Expr {
															return ast2.ExprStructLitExprCtor(v_56.F0, convertStructLitFields(v_56.F1))
														}()
													} else {
														if v_55, ok := e.(parser2.ExprInlineGoExpr); ok {
															return func() ast2.Expr {
																t_71 := convertType(*v_55.F0)
																return ast2.ExprInlineGoExprCtor(&t_71, v_55.F1)
															}()
														} else {
															panic("unreachable")
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}()
}
func convertStructLitFields(items []parser2.StructLitField) []ast2.StructLitField {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(f parser2.StructLitField) ast2.StructLitField {
		return ast2.StructLitField{Name: f.Name, Value: convertExpr(f.Value)}
	})
}
func convertStmts(items []parser2.Stmt) []ast2.Stmt {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(s parser2.Stmt) ast2.Stmt {
		return convertStmt(s)
	})
}
func convertExprs(items []parser2.Expr) []ast2.Expr {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(e parser2.Expr) ast2.Expr {
		return convertExpr(e)
	})
}
func convertParam(p parser2.Param) ast2.Param {
	return ast2.Param{Name: p.Name, Type: convertType(p.Type)}
}
func convertParams(items []parser2.Param) []ast2.Param {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(p parser2.Param) ast2.Param {
		return convertParam(p)
	})
}
func convertField(f parser2.Field) ast2.Field {
	return ast2.Field{Name: f.Name, Type: convertType(f.Type), Tag: f.Tag}
}
func convertFields(items []parser2.Field) []ast2.Field {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(f parser2.Field) ast2.Field {
		return convertField(f)
	})
}
func convertVariant(v parser2.Variant) ast2.Variant {
	return ast2.Variant{Name: v.Name, Fields: convertTypes(v.Fields)}
}
func convertVariants(items []parser2.Variant) []ast2.Variant {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(v parser2.Variant) ast2.Variant {
		return convertVariant(v)
	})
}
func convertFuncSig(sig parser2.FuncSig) ast2.FuncSig {
	return ast2.FuncSig{Name: sig.Name, TypeParams: sig.TypeParams, Params: convertParams(sig.Params), Ret: convertTypeOption(sig.Ret)}
}
func convertFuncSigs(items []parser2.FuncSig) []ast2.FuncSig {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(sig parser2.FuncSig) ast2.FuncSig {
		return convertFuncSig(sig)
	})
}
func convertImplMethod(m parser2.ImplMethod) ast2.ImplMethod {
	return ast2.ImplMethod{Sig: convertFuncSig(m.Sig), Body: convertExpr(m.Body)}
}
func convertImplMethods(items []parser2.ImplMethod) []ast2.ImplMethod {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(items, func(m parser2.ImplMethod) ast2.ImplMethod {
		return convertImplMethod(m)
	})
}
