// Code generated by mygo; DO NOT EDIT.

package codegen2

import (
	"strconv"
	"strings"

	"github.com/mygo-lang/mygo/internal/mygo/ast2"
	. "github.com/mygo-lang/mygo/prelude"
)

type TypeArgParts struct {
	Name string
	Args []string
}

func goType(t ast2.TypeExpr, typeParams map[string]struct{}) string {
	var expr_697 string
	if v_268, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_696 string
		var expr_695 string
		if setContainsString(typeParams, v_268.F0) && MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_268.F1) == 0 {
			expr_695 = v_268.F0
		} else {
			var expr_694 string
			if isHKTConstructor(v_268.F0, v_268.F1, typeParams) {
				expr_694 = "HKT[" + v_268.F0 + ", " + hktApplicationArgs(v_268.F1, typeParams) + "]"
			} else {
				var expr_693 string
				fallback_692 := genericNamedType(v_268.F0, v_268.F1, typeParams)
				expr_693 = MygoIT11IEnumerableFN17OptionIEnumerableGN1AEGN6OptionGN1AEN1AEM4Fold(goPrimitiveType(v_268.F0), MygoIN6OptionM8UnwrapOr(goSpecialType(v_268.F0, v_268.F1, typeParams), fallback_692), func(_ string, mapped string) string {
					return mapped
				})
				expr_694 = expr_693
			}
			expr_695 = expr_694
		}
		expr_696 = expr_695
		expr_697 = expr_696
	} else {
		if v_267, ok := t.(ast2.TypeExprFuncType); ok {
			var expr_691 string
			paramStrs_689 := typeExprsToStrings(v_267.F0, typeParams)
			retStr_690 := goType(*v_267.F1, typeParams)
			if retStr_690 == "" || retStr_690 == "struct{}" {
				expr_691 = "func(" + joinStrings(paramStrs_689, ", ") + ")"
			}
			expr_691 = "func(" + joinStrings(paramStrs_689, ", ") + ") " + retStr_690
			expr_697 = expr_691
		} else {
			if v_266, ok := t.(ast2.TypeExprTupleType); ok {
				var expr_688 string
				if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_266.F0) == 0 {
					expr_688 = "struct{}"
				}
				parts_687 := tupleElemsToStrings(v_266.F0, typeParams)
				expr_688 = "struct { " + joinStrings(parts_687, "; ") + " }"
				expr_697 = expr_688
			} else {
				if _, ok := t.(ast2.TypeExprUnitType); ok {
					var expr_686 string
					expr_686 = "struct{}"
					expr_697 = expr_686
				} else {
					{
						var expr_685 string
						expr_685 = "any"
						expr_697 = expr_685
					}
				}
			}
		}
	}
	return expr_697
}
func hktApplicationArgs(args []ast2.TypeExpr, typeParams map[string]struct{}) string {
	var expr_701 string
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		expr_701 = "any"
	} else {
		var expr_700 string
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
			expr_700 = goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams)
		} else {
			var expr_699 string
			first_698 := goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams)
			expr_699 = "HKT[" + first_698 + ", " + hktApplicationArgs(sliceDrop[ast2.TypeExpr](args, 1), typeParams) + "]"
			expr_700 = expr_699
		}
		expr_701 = expr_700
	}
	return expr_701
}
func isHKTConstructor(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) bool {
	var expr_702 bool
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		expr_702 = false
	} else {
		expr_702 = setContainsString(typeParams, name+"#hkt")
	}
	return expr_702
}
func genericNamedType(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) string {
	var expr_705 string
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		expr_705 = name
	} else {
		var expr_704 string
		argStrs_703 := typeArgsToStrings(args, typeParams)
		expr_704 = name + "[" + joinStrings(argStrs_703, ", ") + "]"
		expr_705 = expr_704
	}
	return expr_705
}
func goPrimitiveType(name string) Option[string] {
	var expr_725 Option[string]
	if name == "Int" {
		var expr_724 Option[string]
		expr_724 = Some[string]("int")
		expr_725 = expr_724
	} else {
		if name == "Int8" {
			var expr_723 Option[string]
			expr_723 = Some[string]("int8")
			expr_725 = expr_723
		} else {
			if name == "Int16" {
				var expr_722 Option[string]
				expr_722 = Some[string]("int16")
				expr_725 = expr_722
			} else {
				if name == "Int32" {
					var expr_721 Option[string]
					expr_721 = Some[string]("int32")
					expr_725 = expr_721
				} else {
					if name == "Int64" {
						var expr_720 Option[string]
						expr_720 = Some[string]("int64")
						expr_725 = expr_720
					} else {
						if name == "UInt" {
							var expr_719 Option[string]
							expr_719 = Some[string]("uint")
							expr_725 = expr_719
						} else {
							if name == "UInt8" {
								var expr_718 Option[string]
								expr_718 = Some[string]("uint8")
								expr_725 = expr_718
							} else {
								if name == "UInt16" {
									var expr_717 Option[string]
									expr_717 = Some[string]("uint16")
									expr_725 = expr_717
								} else {
									if name == "UInt32" {
										var expr_716 Option[string]
										expr_716 = Some[string]("uint32")
										expr_725 = expr_716
									} else {
										if name == "UInt64" {
											var expr_715 Option[string]
											expr_715 = Some[string]("uint64")
											expr_725 = expr_715
										} else {
											if name == "Byte" {
												var expr_714 Option[string]
												expr_714 = Some[string]("byte")
												expr_725 = expr_714
											} else {
												if name == "Rune" {
													var expr_713 Option[string]
													expr_713 = Some[string]("rune")
													expr_725 = expr_713
												} else {
													if name == "Float32" {
														var expr_712 Option[string]
														expr_712 = Some[string]("float32")
														expr_725 = expr_712
													} else {
														if name == "Float64" {
															var expr_711 Option[string]
															expr_711 = Some[string]("float64")
															expr_725 = expr_711
														} else {
															if name == "String" {
																var expr_710 Option[string]
																expr_710 = Some[string]("string")
																expr_725 = expr_710
															} else {
																if name == "Bool" {
																	var expr_709 Option[string]
																	expr_709 = Some[string]("bool")
																	expr_725 = expr_709
																} else {
																	if name == "Any" {
																		var expr_708 Option[string]
																		expr_708 = Some[string]("any")
																		expr_725 = expr_708
																	} else {
																		if name == "Unit" {
																			var expr_707 Option[string]
																			expr_707 = Some[string]("struct{}")
																			expr_725 = expr_707
																		} else {
																			{
																				var expr_706 Option[string]
																				expr_706 = None[string]()
																				expr_725 = expr_706
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_725
}
func goSpecialType(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	var expr_734 Option[string]
	if name == "Ref" {
		var expr_733 Option[string]
		expr_733 = unarySpecialType(args, typeParams, "*")
		expr_734 = expr_733
	} else {
		if name == "Slice" {
			var expr_732 Option[string]
			expr_732 = unarySpecialType(args, typeParams, "[]")
			expr_734 = expr_732
		} else {
			if name == "Map" {
				var expr_731 Option[string]
				expr_731 = mapSpecialType(args, typeParams)
				expr_734 = expr_731
			} else {
				if name == "Set" {
					var expr_730 Option[string]
					expr_730 = setSpecialType(args, typeParams)
					expr_734 = expr_730
				} else {
					if name == "Chan" {
						var expr_729 Option[string]
						expr_729 = unarySpecialType(args, typeParams, "chan ")
						expr_734 = expr_729
					} else {
						if name == "SendChan" {
							var expr_728 Option[string]
							expr_728 = unarySpecialType(args, typeParams, "chan<- ")
							expr_734 = expr_728
						} else {
							if name == "RecvChan" {
								var expr_727 Option[string]
								expr_727 = unarySpecialType(args, typeParams, "<-chan ")
								expr_734 = expr_727
							} else {
								{
									var expr_726 Option[string]
									expr_726 = None[string]()
									expr_734 = expr_726
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_734
}
func unarySpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}, prefix string) Option[string] {
	var expr_735 Option[string]
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
		expr_735 = Some[string](prefix + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams))
	} else {
		expr_735 = None[string]()
	}
	return expr_735
}
func mapSpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	var expr_736 Option[string]
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 2 {
		expr_736 = Some[string]("map[" + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams) + "]" + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 1), ast2.TypeExprUnitTypeCtor()), typeParams))
	} else {
		expr_736 = None[string]()
	}
	return expr_736
}
func setSpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	var expr_737 Option[string]
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
		expr_737 = Some[string]("map[" + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams) + "]struct{}")
	} else {
		expr_737 = None[string]()
	}
	return expr_737
}
func goReturnType(t ast2.TypeExpr, typeParams map[string]struct{}) string {
	if isUnitType(t) {
		return ""
	}
	return goType(t, typeParams)
}
func goReturnTypes(t ast2.TypeExpr, typeParams map[string]struct{}) []string {
	var expr_742 []string
	if v_269, ok := t.(ast2.TypeExprTupleType); ok {
		var expr_741 []string
		expr_741 = MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(v_269.F0, func(item ast2.TypeExpr) string {
			return goType(item, typeParams)
		})
		expr_742 = expr_741
	} else {
		{
			var expr_740 []string
			rt_738 := goReturnType(t, typeParams)
			var expr_739 []string
			if rt_738 != "" {
				expr_739 = []string{rt_738}
			} else {
				expr_739 = []string([]string{})
			}
			expr_740 = expr_739
			expr_742 = expr_740
		}
	}
	return expr_742
}
func isUnitType(t ast2.TypeExpr) bool {
	var expr_747 bool
	if _, ok := t.(ast2.TypeExprUnitType); ok {
		var expr_746 bool
		expr_746 = true
		expr_747 = expr_746
	} else {
		if v_271, ok := t.(ast2.TypeExprTupleType); ok {
			var expr_745 bool
			expr_745 = MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_271.F0) == 0
			expr_747 = expr_745
		} else {
			if v_270, ok := t.(ast2.TypeExprNamedType); ok {
				var expr_744 bool
				expr_744 = v_270.F0 == "Unit" && MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_270.F1) == 0
				expr_747 = expr_744
			} else {
				{
					var expr_743 bool
					expr_743 = false
					expr_747 = expr_743
				}
			}
		}
	}
	return expr_747
}
func isUnitGoType(typ string) bool {
	trimmed_748 := strings.TrimSpace(typ)
	return trimmed_748 == "Unit" || trimmed_748 == "struct{}" || trimmed_748 == "()"
}
func setContainsString(items map[string]struct{}, target string) bool {
	return MygoIT11IEnumerableFN14SetIEnumerableGN1AEGN3SetGN1AEN1AEM4Fold(items, false, func(found bool, current string) bool {
		return found || current == target
	})
}
func typeParamSet(params []string) map[string]struct{} {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(params, MygoIN3SetM3New[string](), func(s map[string]struct{}, p string) map[string]struct{} {
		MygoIN3SetM3Add(s, p)
		var expr_749 map[string]struct{}
		if strings.HasPrefix(p, hktTypeParamName(p)+"[") {
			expr_749 = MygoIN3SetM3Add(s, hktTypeParamName(p)+"#hkt")
		} else {
			expr_749 = s
		}
		return expr_749
	})
}
func sanitizeIdent(s string) string {
	var result_750 string = func() string {
		var b strings.Builder
		for i, r := range s {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
				if i == 0 && r >= '0' && r <= '9' {
					b.WriteRune('_')
				}
				b.WriteRune(r)
				continue
			}
			b.WriteRune('_')
		}
		return b.String()
	}()
	if MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(result_750) == 0 {
		return "_"
	}
	if isGoKeyword(result_750) {
		return result_750 + "_"
	}
	return result_750
}
func isGoKeyword(s string) bool {
	var expr_777 bool
	if s == "break" {
		var expr_776 bool
		expr_776 = true
		expr_777 = expr_776
	} else {
		if s == "case" {
			var expr_775 bool
			expr_775 = true
			expr_777 = expr_775
		} else {
			if s == "chan" {
				var expr_774 bool
				expr_774 = true
				expr_777 = expr_774
			} else {
				if s == "const" {
					var expr_773 bool
					expr_773 = true
					expr_777 = expr_773
				} else {
					if s == "continue" {
						var expr_772 bool
						expr_772 = true
						expr_777 = expr_772
					} else {
						if s == "default" {
							var expr_771 bool
							expr_771 = true
							expr_777 = expr_771
						} else {
							if s == "defer" {
								var expr_770 bool
								expr_770 = true
								expr_777 = expr_770
							} else {
								if s == "else" {
									var expr_769 bool
									expr_769 = true
									expr_777 = expr_769
								} else {
									if s == "fallthrough" {
										var expr_768 bool
										expr_768 = true
										expr_777 = expr_768
									} else {
										if s == "for" {
											var expr_767 bool
											expr_767 = true
											expr_777 = expr_767
										} else {
											if s == "func" {
												var expr_766 bool
												expr_766 = true
												expr_777 = expr_766
											} else {
												if s == "go" {
													var expr_765 bool
													expr_765 = true
													expr_777 = expr_765
												} else {
													if s == "goto" {
														var expr_764 bool
														expr_764 = true
														expr_777 = expr_764
													} else {
														if s == "if" {
															var expr_763 bool
															expr_763 = true
															expr_777 = expr_763
														} else {
															if s == "import" {
																var expr_762 bool
																expr_762 = true
																expr_777 = expr_762
															} else {
																if s == "interface" {
																	var expr_761 bool
																	expr_761 = true
																	expr_777 = expr_761
																} else {
																	if s == "map" {
																		var expr_760 bool
																		expr_760 = true
																		expr_777 = expr_760
																	} else {
																		if s == "package" {
																			var expr_759 bool
																			expr_759 = true
																			expr_777 = expr_759
																		} else {
																			if s == "range" {
																				var expr_758 bool
																				expr_758 = true
																				expr_777 = expr_758
																			} else {
																				if s == "return" {
																					var expr_757 bool
																					expr_757 = true
																					expr_777 = expr_757
																				} else {
																					if s == "select" {
																						var expr_756 bool
																						expr_756 = true
																						expr_777 = expr_756
																					} else {
																						if s == "struct" {
																							var expr_755 bool
																							expr_755 = true
																							expr_777 = expr_755
																						} else {
																							if s == "switch" {
																								var expr_754 bool
																								expr_754 = true
																								expr_777 = expr_754
																							} else {
																								if s == "type" {
																									var expr_753 bool
																									expr_753 = true
																									expr_777 = expr_753
																								} else {
																									if s == "var" {
																										var expr_752 bool
																										expr_752 = true
																										expr_777 = expr_752
																									} else {
																										{
																											var expr_751 bool
																											expr_751 = false
																											expr_777 = expr_751
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_777
}
func inherentReceiverName(t ast2.TypeExpr) string {
	var expr_780 string
	if v_273, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_779 string
		expr_779 = v_273.F0
		expr_780 = expr_779
	} else {
		{
			var expr_778 string
			expr_778 = ""
			expr_780 = expr_778
		}
	}
	return expr_780
}
func inherentMethodName(receiverName string, methodName string) string {
	return implMethodSymbol(mangleInherentImplSymbol(receiverName), methodName)
}
func variantGoTypeName(enumName string, variant string) string {
	if enumName == "" {
		return variant
	}
	return enumName + variant
}
func enumConstructorGoName(enumName string, variantName string) string {
	if (enumName == "Option" || enumName == "Result") && (variantName == "Some" || variantName == "None" || variantName == "Ok" || variantName == "Err") {
		return variantName
	}
	return variantNameForEnum(enumName, variantName) + "Ctor"
}
func variantNameForEnum(enumName string, variantName string) string {
	if enumName == "" {
		return variantName
	}
	return enumName + variantName
}
func helperFuncName(method string, typeKey string) string {
	cleaned_781 := strings.TrimPrefix(typeKey, "_")
	return implMethodSymbol(sanitizeIdent(cleaned_781), method)
}
func implMethodSymbol(implSymbol string, methodName string) string {
	return sanitizeIdent(implSymbol + "M" + mangleComponent(methodName))
}
func mangleInherentImplSymbol(receiverName string) string {
	return "MygoIN" + mangleComponent(receiverName)
}
func mangleInterfaceImplSymbol(ifaceName string, implType ast2.TypeExpr, args []ast2.TypeExpr) string {
	out_782 := "MygoIT" + mangleComponent(ifaceName) + "F" + mangleTypeExpr(implType) + "G"
	var i_783 int = 0
	for i_783 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) {
		out_782 = out_782 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, i_783), ast2.TypeExprUnitTypeCtor()))
		i_783 = i_783 + 1
	}
	return sanitizeIdent(out_782 + "E")
}
func mangleComponent(s string) string {
	clean_784 := sanitizeIdent(s)
	return strconv.Itoa(MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(clean_784)) + clean_784
}
func mangleTypeExpr(t ast2.TypeExpr) string {
	var expr_795 string
	if v_277, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_794 string
		out_792 := "N" + mangleComponent(canonicalMyGoTypeName(v_277.F0))
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_277.F1) > 0 {
			out_792 = out_792 + "G"
			var i_793 int = 0
			for i_793 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_277.F1) {
				out_792 = out_792 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_277.F1, i_793), ast2.TypeExprUnitTypeCtor()))
				i_793 = i_793 + 1
			}
			out_792 = out_792 + "E"
		}
		expr_794 = out_792
		expr_795 = expr_794
	} else {
		if v_276, ok := t.(ast2.TypeExprFuncType); ok {
			var expr_791 string
			out_789 := "F"
			var i_790 int = 0
			for i_790 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_276.F0) {
				out_789 = out_789 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_276.F0, i_790), ast2.TypeExprUnitTypeCtor()))
				i_790 = i_790 + 1
			}
			expr_791 = out_789 + "R" + mangleTypeExpr(*v_276.F1) + "E"
			expr_795 = expr_791
		} else {
			if v_275, ok := t.(ast2.TypeExprTupleType); ok {
				var expr_788 string
				out_786 := "U"
				var i_787 int = 0
				for i_787 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_275.F0) {
					out_786 = out_786 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_275.F0, i_787), ast2.TypeExprUnitTypeCtor()))
					i_787 = i_787 + 1
				}
				expr_788 = out_786 + "E"
				expr_795 = expr_788
			} else {
				if _, ok := t.(ast2.TypeExprUnitType); ok {
					var expr_785 string
					expr_785 = "X" + mangleComponent("Unit")
					expr_795 = expr_785
				} else {
					panic("unreachable")
				}
			}
		}
	}
	return expr_795
}
func canonicalMyGoTypeName(name string) string {
	var expr_812 string
	if name == "int" {
		var expr_811 string
		expr_811 = "Int"
		expr_812 = expr_811
	} else {
		if name == "int8" {
			var expr_810 string
			expr_810 = "Int8"
			expr_812 = expr_810
		} else {
			if name == "uint8" {
				var expr_809 string
				expr_809 = "UInt8"
				expr_812 = expr_809
			} else {
				if name == "int16" {
					var expr_808 string
					expr_808 = "Int16"
					expr_812 = expr_808
				} else {
					if name == "uint16" {
						var expr_807 string
						expr_807 = "UInt16"
						expr_812 = expr_807
					} else {
						if name == "int32" {
							var expr_806 string
							expr_806 = "Int32"
							expr_812 = expr_806
						} else {
							if name == "uint32" {
								var expr_805 string
								expr_805 = "UInt32"
								expr_812 = expr_805
							} else {
								if name == "int64" {
									var expr_804 string
									expr_804 = "Int64"
									expr_812 = expr_804
								} else {
									if name == "uint" {
										var expr_803 string
										expr_803 = "UInt"
										expr_812 = expr_803
									} else {
										if name == "uint64" {
											var expr_802 string
											expr_802 = "UInt64"
											expr_812 = expr_802
										} else {
											if name == "float32" {
												var expr_801 string
												expr_801 = "Float32"
												expr_812 = expr_801
											} else {
												if name == "float64" {
													var expr_800 string
													expr_800 = "Float64"
													expr_812 = expr_800
												} else {
													if name == "string" {
														var expr_799 string
														expr_799 = "String"
														expr_812 = expr_799
													} else {
														if name == "bool" {
															var expr_798 string
															expr_798 = "Bool"
															expr_812 = expr_798
														} else {
															if name == "any" {
																var expr_797 string
																expr_797 = "Any"
																expr_812 = expr_797
															} else {
																{
																	var expr_796 string
																	expr_796 = name
																	expr_812 = expr_796
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_812
}
func typeKeyFromType(typ string) string {
	step1_813 := strings.ReplaceAll(typ, "[", "_")
	step2_814 := strings.ReplaceAll(step1_813, "]", "")
	step3_815 := strings.ReplaceAll(step2_814, ", ", "_")
	step4_816 := strings.ReplaceAll(step3_815, ",", "_")
	step5_817 := strings.ReplaceAll(step4_816, " ", "")
	step6_818 := strings.ReplaceAll(step5_817, "*", "Ptr")
	step7_819 := strings.ReplaceAll(step6_818, ".", "_")
	step8_820 := strings.ReplaceAll(step7_819, "func(", "Func_")
	step9_821 := strings.ReplaceAll(step8_820, ")", "")
	return sanitizeIdent(strings.ToLower(step9_821))
}
func typeclassFuncType(paramTypes []string, retType string) string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(paramTypes) == 0 {
		if retType == "" {
			return "func()"
		}
		return "func() " + retType
	}
	var fn_822 string = "func(" + joinStrings(paramTypes, ", ") + ")"
	if retType != "" {
		fn_822 = fn_822 + " " + retType
	}
	return fn_822
}
func typeArgsToStrings(args []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		return []string([]string{})
	}
	head_823 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor())
	tail_824 := typeArgsToStrings(sliceDrop[ast2.TypeExpr](args, 1), typeParams)
	return MygoIN5SliceM7Prepend(tail_824, goType(head_823, typeParams))
}
func typeExprsToStrings(items []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return []string([]string{})
	}
	head_825 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), ast2.TypeExprUnitTypeCtor())
	tail_826 := typeExprsToStrings(sliceDrop[ast2.TypeExpr](items, 1), typeParams)
	return MygoIN5SliceM7Prepend(tail_826, goType(head_825, typeParams))
}
func tupleElemsToStrings(elems []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems) == 0 {
		return []string([]string{})
	}
	head_827 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(elems, 0), ast2.TypeExprUnitTypeCtor())
	tail_828 := tupleElemsToStrings(sliceDrop[ast2.TypeExpr](elems, 1), typeParams)
	i_829 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems) - MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems)
	return MygoIN5SliceM7Prepend(tail_828, "F"+MygoIT8ToStringFN3IntGN3IntEM8ToString(i_829)+" "+goType(head_827, typeParams))
}
func joinStrings(items []string, sep string) string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return ""
	}
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 1 {
		return MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), "")
	}
	head_830 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), "")
	tail_831 := joinStrings(sliceDrop[string](items, 1), sep)
	return head_830 + sep + tail_831
}
func sliceDrop[A any](items []A, n int) []A {
	if n <= 0 {
		return items
	}
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return items
	}
	return sliceDrop[A](sliceTail[A](items), n-1)
}
func sliceTail[A any](items []A) []A {
	return sliceTailLoop[A](items, 1, []A([]A{}))
}
func sliceTailLoop[A any](items []A, index int, out []A) []A {
	if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) {
		return out
	}
	item_832 := MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index)
	var expr_835 []A
	if v_279, ok := item_832.(OptionSome[A]); ok {
		var expr_834 []A
		expr_834 = sliceTailLoop[A](items, index+1, MygoIN5SliceM6Append(out, v_279.F0))
		expr_835 = expr_834
	} else {
		if _, ok := item_832.(OptionNone[A]); ok {
			var expr_833 []A
			expr_833 = out
			expr_835 = expr_833
		} else {
			panic("unreachable")
		}
	}
	return expr_835
}
func importPathForGo(path string) string {
	return strings.TrimPrefix(path, "go:")
}
func importAliasForPath(path string) string {
	cleanPath_836 := importPathForGo(path)
	if cleanPath_836 == "" {
		return ""
	}
	trimmed_837 := strings.TrimSuffix(cleanPath_836, "/")
	parts_838 := strings.Split(trimmed_837, "/")
	return toPackageName(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(parts_838, MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(parts_838)-1), trimmed_837))
}
func toPackageName(name string) string {
	if name == "" {
		return "main"
	}
	return strings.ToLower(sanitizeIdent(name))
}
func exportName(name string) string {
	if name == "" {
		return name
	}
	first_839 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(name, 0, 1), "")
	rest_840 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(name, 1, MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(name)), "")
	return MygoIN6StringM7ToUpper(first_839) + rest_840
}
func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return 'a' - ('a' - 'A')
	}
	return r
}
func splitTypeArgs(typ string) TypeArgParts {
	clean_841 := strings.TrimSpace(typ)
	if clean_841 == "" {
		return TypeArgParts{Name: "", Args: []string([]string{})}
	}
	idx_842 := strings.Index(clean_841, "[")
	if idx_842 < 0 {
		return TypeArgParts{Name: clean_841, Args: []string([]string{})}
	}
	endPos_843 := matchingTypeArgEnd(clean_841, idx_842)
	if endPos_843 < 0 || endPos_843 < idx_842 {
		return TypeArgParts{Name: clean_841, Args: []string([]string{})}
	}
	name_844 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(clean_841, 0, idx_842), "")
	inner_845 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(clean_841, idx_842+1, endPos_843), "")
	if inner_845 == "" {
		return TypeArgParts{Name: name_844, Args: []string([]string{})}
	}
	return TypeArgParts{Name: name_844, Args: splitTopLevel(inner_845, ',')}
}
func matchingTypeArgEnd(typ string, open int) int {
	return func() int {
		depth := 0
		for i, r := range typ[open:] {
			switch r {
			case '[':
				depth++
			case ']':
				depth--
				if depth == 0 {
					return open + i
				}
			}
		}
		return -1
	}()
}
func splitTopLevel(s string, sep rune) []string {
	return func() []string {
		parts := []string{}
		depth := 0
		start := 0
		for i, r := range s {
			switch r {
			case '[', '(':
				depth++
			case ']', ')':
				if depth > 0 {
					depth--
				}
			default:
				if r == sep && depth == 0 {
					parts = append(parts, strings.TrimSpace(s[start:i]))
					start = i + len(string(r))
				}
			}
		}
		parts = append(parts, strings.TrimSpace(s[start:]))
		return parts
	}()
}
func isInherentReceiverParam(paramType ast2.TypeExpr, implType ast2.TypeExpr) bool {
	return typeString(paramType) == typeString(implType)
}
func typeString(t ast2.TypeExpr) string {
	var expr_852 string
	if v_281, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_851 string
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_281.F1) == 0 {
			expr_851 = v_281.F0
		}
		argStrs_850 := typeArgsToStrings(v_281.F1, MygoIN3SetM3New[string]())
		expr_851 = v_281.F0 + "[" + joinStrings(argStrs_850, ", ") + "]"
		expr_852 = expr_851
	} else {
		if v_280, ok := t.(ast2.TypeExprFuncType); ok {
			var expr_849 string
			paramStrs_847 := typeExprsToStrings(v_280.F0, MygoIN3SetM3New[string]())
			retStr_848 := typeString(*v_280.F1)
			if retStr_848 == "" {
				expr_849 = "func(" + joinStrings(paramStrs_847, ", ") + ")"
			}
			expr_849 = "func(" + joinStrings(paramStrs_847, ", ") + ") " + retStr_848
			expr_852 = expr_849
		} else {
			{
				var expr_846 string
				expr_846 = "any"
				expr_852 = expr_846
			}
		}
	}
	return expr_852
}
