// Code generated by mygo; DO NOT EDIT.

package codegen2

import (
	"strconv"
	"strings"

	"github.com/mygo-lang/mygo/internal/mygo/ast2"
	. "github.com/mygo-lang/mygo/prelude"
)

type TypeArgParts struct {
	Name string
	Args []string
}

func goType(t ast2.TypeExpr, typeParams map[string]struct{}) string {
	return func() string {
		if v_197, ok := t.(ast2.TypeExprNamedType); ok {
			return func() string {
				if setContainsString(typeParams, v_197.F0) && MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_197.F1) == 0 {
					return v_197.F0
				}
				fallback_124 := genericNamedType(v_197.F0, v_197.F1, typeParams)
				return MygoIT11IEnumerableFN17OptionIEnumerableGN1AEGN6OptionGN1AEN1AEM4Fold(goPrimitiveType(v_197.F0), MygoIN6OptionM8UnwrapOr(goSpecialType(v_197.F0, v_197.F1, typeParams), fallback_124), func(_ string, mapped string) string {
					return mapped
				})
			}()
		} else {
			if v_196, ok := t.(ast2.TypeExprFuncType); ok {
				return func() string {
					paramStrs_122 := typeExprsToStrings(v_196.F0, typeParams)
					retStr_123 := goType(*v_196.F1, typeParams)
					if retStr_123 == "" || retStr_123 == "struct{}" {
						return "func(" + joinStrings(paramStrs_122, ", ") + ")"
					}
					return "func(" + joinStrings(paramStrs_122, ", ") + ") " + retStr_123
				}()
			} else {
				if v_195, ok := t.(ast2.TypeExprTupleType); ok {
					return func() string {
						if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_195.F0) == 0 {
							return "struct{}"
						}
						parts_121 := tupleElemsToStrings(v_195.F0, typeParams)
						return "struct { " + joinStrings(parts_121, "; ") + " }"
					}()
				} else {
					if _, ok := t.(ast2.TypeExprUnitType); ok {
						return func() string {
							return "struct{}"
						}()
					} else {
						return func() string {
							return "any"
						}()
					}
				}
			}
		}
	}()
}
func genericNamedType(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) string {
	return func() string {
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
			return name
		} else {
			return func() string {
				argStrs_125 := typeArgsToStrings(args, typeParams)
				return name + "[" + joinStrings(argStrs_125, ", ") + "]"
			}()
		}
	}()
}
func goPrimitiveType(name string) Option[string] {
	return func() Option[string] {
		if name == "Int" {
			return func() Option[string] {
				return Some[string]("int")
			}()
		} else {
			if name == "Int8" {
				return func() Option[string] {
					return Some[string]("int8")
				}()
			} else {
				if name == "Int16" {
					return func() Option[string] {
						return Some[string]("int16")
					}()
				} else {
					if name == "Int32" {
						return func() Option[string] {
							return Some[string]("int32")
						}()
					} else {
						if name == "Int64" {
							return func() Option[string] {
								return Some[string]("int64")
							}()
						} else {
							if name == "UInt" {
								return func() Option[string] {
									return Some[string]("uint")
								}()
							} else {
								if name == "UInt8" {
									return func() Option[string] {
										return Some[string]("uint8")
									}()
								} else {
									if name == "UInt16" {
										return func() Option[string] {
											return Some[string]("uint16")
										}()
									} else {
										if name == "UInt32" {
											return func() Option[string] {
												return Some[string]("uint32")
											}()
										} else {
											if name == "UInt64" {
												return func() Option[string] {
													return Some[string]("uint64")
												}()
											} else {
												if name == "Byte" {
													return func() Option[string] {
														return Some[string]("byte")
													}()
												} else {
													if name == "Rune" {
														return func() Option[string] {
															return Some[string]("rune")
														}()
													} else {
														if name == "Float32" {
															return func() Option[string] {
																return Some[string]("float32")
															}()
														} else {
															if name == "Float64" {
																return func() Option[string] {
																	return Some[string]("float64")
																}()
															} else {
																if name == "String" {
																	return func() Option[string] {
																		return Some[string]("string")
																	}()
																} else {
																	if name == "Bool" {
																		return func() Option[string] {
																			return Some[string]("bool")
																		}()
																	} else {
																		if name == "Any" {
																			return func() Option[string] {
																				return Some[string]("any")
																			}()
																		} else {
																			if name == "Unit" {
																				return func() Option[string] {
																					return Some[string]("struct{}")
																				}()
																			} else {
																				return func() Option[string] {
																					return None[string]()
																				}()
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}()
}
func goSpecialType(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	return func() Option[string] {
		if name == "Ref" {
			return func() Option[string] {
				return unarySpecialType(args, typeParams, "*")
			}()
		} else {
			if name == "Slice" {
				return func() Option[string] {
					return unarySpecialType(args, typeParams, "[]")
				}()
			} else {
				if name == "Map" {
					return func() Option[string] {
						return mapSpecialType(args, typeParams)
					}()
				} else {
					if name == "Set" {
						return func() Option[string] {
							return setSpecialType(args, typeParams)
						}()
					} else {
						if name == "Chan" {
							return func() Option[string] {
								return unarySpecialType(args, typeParams, "chan ")
							}()
						} else {
							if name == "SendChan" {
								return func() Option[string] {
									return unarySpecialType(args, typeParams, "chan<- ")
								}()
							} else {
								if name == "RecvChan" {
									return func() Option[string] {
										return unarySpecialType(args, typeParams, "<-chan ")
									}()
								} else {
									return func() Option[string] {
										return None[string]()
									}()
								}
							}
						}
					}
				}
			}
		}
	}()
}
func unarySpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}, prefix string) Option[string] {
	return func() Option[string] {
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
			return Some[string](prefix + goType(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams))
		} else {
			return None[string]()
		}
	}()
}
func mapSpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	return func() Option[string] {
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 2 {
			return Some[string]("map[" + goType(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams) + "]" + goType(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 1), ast2.TypeExprUnitTypeCtor()), typeParams))
		} else {
			return None[string]()
		}
	}()
}
func setSpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	return func() Option[string] {
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
			return Some[string]("map[" + goType(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams) + "]struct{}")
		} else {
			return None[string]()
		}
	}()
}
func goReturnType(t ast2.TypeExpr, typeParams map[string]struct{}) string {
	if isUnitType(t) {
		return ""
	}
	return goType(t, typeParams)
}
func goReturnTypes(t ast2.TypeExpr, typeParams map[string]struct{}) []string {
	return func() []string {
		if v_198, ok := t.(ast2.TypeExprTupleType); ok {
			return func() []string {
				return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(v_198.F0, func(item ast2.TypeExpr) string {
					return goType(item, typeParams)
				})
			}()
		} else {
			return func() []string {
				rt_126 := goReturnType(t, typeParams)
				if rt_126 != "" {
					return []string{rt_126}
				}
				return []string([]string{})
			}()
		}
	}()
}
func isUnitType(t ast2.TypeExpr) bool {
	return func() bool {
		if _, ok := t.(ast2.TypeExprUnitType); ok {
			return func() bool {
				return true
			}()
		} else {
			if v_200, ok := t.(ast2.TypeExprTupleType); ok {
				return func() bool {
					return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_200.F0) == 0
				}()
			} else {
				if v_199, ok := t.(ast2.TypeExprNamedType); ok {
					return func() bool {
						return v_199.F0 == "Unit" && MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_199.F1) == 0
					}()
				} else {
					return func() bool {
						return false
					}()
				}
			}
		}
	}()
}
func isUnitGoType(typ string) bool {
	trimmed_127 := strings.TrimSpace(typ)
	return trimmed_127 == "Unit" || trimmed_127 == "struct{}" || trimmed_127 == "()"
}
func setContainsString(items map[string]struct{}, target string) bool {
	return MygoIT11IEnumerableFN14SetIEnumerableGN1AEGN3SetGN1AEN1AEM4Fold(items, false, func(found bool, current string) bool {
		return found || current == target
	})
}
func typeParamSet(params []string) map[string]struct{} {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(params, MygoIN3SetM3New[string](), func(s map[string]struct{}, p string) map[string]struct{} {
		return MygoIN3SetM3Add(s, p)
	})
}
func sanitizeIdent(s string) string {
	var result_128 string = func() string {
		var b strings.Builder
		for i, r := range s {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
				if i == 0 && r >= '0' && r <= '9' {
					b.WriteRune('_')
				}
				b.WriteRune(r)
				continue
			}
			b.WriteRune('_')
		}
		return b.String()
	}()
	if MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(result_128) == 0 {
		return "_"
	}
	if isGoKeyword(result_128) {
		return result_128 + "_"
	}
	return result_128
}
func isGoKeyword(s string) bool {
	return func() bool {
		if s == "break" {
			return func() bool {
				return true
			}()
		} else {
			if s == "case" {
				return func() bool {
					return true
				}()
			} else {
				if s == "chan" {
					return func() bool {
						return true
					}()
				} else {
					if s == "const" {
						return func() bool {
							return true
						}()
					} else {
						if s == "continue" {
							return func() bool {
								return true
							}()
						} else {
							if s == "default" {
								return func() bool {
									return true
								}()
							} else {
								if s == "defer" {
									return func() bool {
										return true
									}()
								} else {
									if s == "else" {
										return func() bool {
											return true
										}()
									} else {
										if s == "fallthrough" {
											return func() bool {
												return true
											}()
										} else {
											if s == "for" {
												return func() bool {
													return true
												}()
											} else {
												if s == "func" {
													return func() bool {
														return true
													}()
												} else {
													if s == "go" {
														return func() bool {
															return true
														}()
													} else {
														if s == "goto" {
															return func() bool {
																return true
															}()
														} else {
															if s == "if" {
																return func() bool {
																	return true
																}()
															} else {
																if s == "import" {
																	return func() bool {
																		return true
																	}()
																} else {
																	if s == "interface" {
																		return func() bool {
																			return true
																		}()
																	} else {
																		if s == "map" {
																			return func() bool {
																				return true
																			}()
																		} else {
																			if s == "package" {
																				return func() bool {
																					return true
																				}()
																			} else {
																				if s == "range" {
																					return func() bool {
																						return true
																					}()
																				} else {
																					if s == "return" {
																						return func() bool {
																							return true
																						}()
																					} else {
																						if s == "select" {
																							return func() bool {
																								return true
																							}()
																						} else {
																							if s == "struct" {
																								return func() bool {
																									return true
																								}()
																							} else {
																								if s == "switch" {
																									return func() bool {
																										return true
																									}()
																								} else {
																									if s == "type" {
																										return func() bool {
																											return true
																										}()
																									} else {
																										if s == "var" {
																											return func() bool {
																												return true
																											}()
																										} else {
																											return func() bool {
																												return false
																											}()
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}()
}
func inherentReceiverName(t ast2.TypeExpr) string {
	return func() string {
		if v_202, ok := t.(ast2.TypeExprNamedType); ok {
			return func() string {
				return v_202.F0
			}()
		} else {
			return func() string {
				return ""
			}()
		}
	}()
}
func inherentMethodName(receiverName string, methodName string) string {
	return implMethodSymbol(mangleInherentImplSymbol(receiverName), methodName)
}
func variantGoTypeName(enumName string, variant string) string {
	if enumName == "" {
		return variant
	}
	return enumName + variant
}
func enumConstructorGoName(enumName string, variantName string) string {
	if (enumName == "Option" || enumName == "Result") && (variantName == "Some" || variantName == "None" || variantName == "Ok" || variantName == "Err") {
		return variantName
	}
	return variantNameForEnum(enumName, variantName) + "Ctor"
}
func variantNameForEnum(enumName string, variantName string) string {
	if enumName == "" {
		return variantName
	}
	return enumName + variantName
}
func helperFuncName(method string, typeKey string) string {
	cleaned_129 := strings.TrimPrefix(typeKey, "_")
	return implMethodSymbol(sanitizeIdent(cleaned_129), method)
}
func implMethodSymbol(implSymbol string, methodName string) string {
	return sanitizeIdent(implSymbol + "M" + mangleComponent(methodName))
}
func mangleInherentImplSymbol(receiverName string) string {
	return "MygoIN" + mangleComponent(receiverName)
}
func mangleInterfaceImplSymbol(ifaceName string, implType ast2.TypeExpr, args []ast2.TypeExpr) string {
	out_130 := "MygoIT" + mangleComponent(ifaceName) + "F" + mangleTypeExpr(implType) + "G"
	var i_131 int = 0
	func() {
		for i_131 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) {
			out_130 = out_130 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, i_131), ast2.TypeExprUnitTypeCtor()))
			i_131 = i_131 + 1
		}
	}()
	return sanitizeIdent(out_130 + "E")
}
func mangleComponent(s string) string {
	clean_132 := sanitizeIdent(s)
	return strconv.Itoa(MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(clean_132)) + clean_132
}
func mangleTypeExpr(t ast2.TypeExpr) string {
	return func() string {
		if v_206, ok := t.(ast2.TypeExprNamedType); ok {
			return func() string {
				out_137 := "N" + mangleComponent(canonicalMyGoTypeName(v_206.F0))
				if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_206.F1) > 0 {
					out_137 = out_137 + "G"
					var i_138 int = 0
					func() {
						for i_138 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_206.F1) {
							out_137 = out_137 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_206.F1, i_138), ast2.TypeExprUnitTypeCtor()))
							i_138 = i_138 + 1
						}
					}()
					out_137 = out_137 + "E"
				}
				return out_137
			}()
		} else {
			if v_205, ok := t.(ast2.TypeExprFuncType); ok {
				return func() string {
					out_135 := "F"
					var i_136 int = 0
					func() {
						for i_136 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_205.F0) {
							out_135 = out_135 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_205.F0, i_136), ast2.TypeExprUnitTypeCtor()))
							i_136 = i_136 + 1
						}
					}()
					return out_135 + "R" + mangleTypeExpr(*v_205.F1) + "E"
				}()
			} else {
				if v_204, ok := t.(ast2.TypeExprTupleType); ok {
					return func() string {
						out_133 := "U"
						var i_134 int = 0
						func() {
							for i_134 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_204.F0) {
								out_133 = out_133 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_204.F0, i_134), ast2.TypeExprUnitTypeCtor()))
								i_134 = i_134 + 1
							}
						}()
						return out_133 + "E"
					}()
				} else {
					if _, ok := t.(ast2.TypeExprUnitType); ok {
						return func() string {
							return "X" + mangleComponent("Unit")
						}()
					} else {
						panic("unreachable")
					}
				}
			}
		}
	}()
}
func canonicalMyGoTypeName(name string) string {
	return func() string {
		if name == "int" {
			return func() string {
				return "Int"
			}()
		} else {
			if name == "int8" {
				return func() string {
					return "Int8"
				}()
			} else {
				if name == "uint8" {
					return func() string {
						return "UInt8"
					}()
				} else {
					if name == "int16" {
						return func() string {
							return "Int16"
						}()
					} else {
						if name == "uint16" {
							return func() string {
								return "UInt16"
							}()
						} else {
							if name == "int32" {
								return func() string {
									return "Int32"
								}()
							} else {
								if name == "uint32" {
									return func() string {
										return "UInt32"
									}()
								} else {
									if name == "int64" {
										return func() string {
											return "Int64"
										}()
									} else {
										if name == "uint" {
											return func() string {
												return "UInt"
											}()
										} else {
											if name == "uint64" {
												return func() string {
													return "UInt64"
												}()
											} else {
												if name == "float32" {
													return func() string {
														return "Float32"
													}()
												} else {
													if name == "float64" {
														return func() string {
															return "Float64"
														}()
													} else {
														if name == "string" {
															return func() string {
																return "String"
															}()
														} else {
															if name == "bool" {
																return func() string {
																	return "Bool"
																}()
															} else {
																if name == "any" {
																	return func() string {
																		return "Any"
																	}()
																} else {
																	return func() string {
																		return name
																	}()
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}()
}
func typeKeyFromType(typ string) string {
	step1_139 := strings.ReplaceAll(typ, "[", "_")
	step2_140 := strings.ReplaceAll(step1_139, "]", "")
	step3_141 := strings.ReplaceAll(step2_140, ", ", "_")
	step4_142 := strings.ReplaceAll(step3_141, ",", "_")
	step5_143 := strings.ReplaceAll(step4_142, " ", "")
	step6_144 := strings.ReplaceAll(step5_143, "*", "Ptr")
	step7_145 := strings.ReplaceAll(step6_144, ".", "_")
	step8_146 := strings.ReplaceAll(step7_145, "func(", "Func_")
	step9_147 := strings.ReplaceAll(step8_146, ")", "")
	return sanitizeIdent(strings.ToLower(step9_147))
}
func typeclassFuncType(paramTypes []string, retType string) string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(paramTypes) == 0 {
		if retType == "" {
			return "func()"
		}
		return "func() " + retType
	}
	var fn_148 string = "func(" + joinStrings(paramTypes, ", ") + ")"
	if retType != "" {
		fn_148 = fn_148 + " " + retType
	}
	return fn_148
}
func typeArgsToStrings(args []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		return []string([]string{})
	}
	head_149 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor())
	tail_150 := typeArgsToStrings(sliceDrop[ast2.TypeExpr](args, 1), typeParams)
	return MygoIN5SliceM7Prepend(tail_150, goType(head_149, typeParams))
}
func typeExprsToStrings(items []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return []string([]string{})
	}
	head_151 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), ast2.TypeExprUnitTypeCtor())
	tail_152 := typeExprsToStrings(sliceDrop[ast2.TypeExpr](items, 1), typeParams)
	return MygoIN5SliceM7Prepend(tail_152, goType(head_151, typeParams))
}
func tupleElemsToStrings(elems []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems) == 0 {
		return []string([]string{})
	}
	head_153 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(elems, 0), ast2.TypeExprUnitTypeCtor())
	tail_154 := tupleElemsToStrings(sliceDrop[ast2.TypeExpr](elems, 1), typeParams)
	i_155 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems) - MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems)
	return MygoIN5SliceM7Prepend(tail_154, "F"+MygoIT8ToStringFN3IntGN3IntEM8ToString(i_155)+" "+goType(head_153, typeParams))
}
func joinStrings(items []string, sep string) string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return ""
	}
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 1 {
		return MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), "")
	}
	head_156 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), "")
	tail_157 := joinStrings(sliceDrop[string](items, 1), sep)
	return head_156 + sep + tail_157
}
func sliceDrop[A any](items []A, n int) []A {
	if n <= 0 {
		return items
	}
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return items
	}
	return sliceDrop[A](sliceTail[A](items), n-1)
}
func sliceTail[A any](items []A) []A {
	return sliceTailLoop[A](items, 1, []A([]A{}))
}
func sliceTailLoop[A any](items []A, index int, out []A) []A {
	if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) {
		return out
	}
	item_158 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index)
	return func() []A {
		if v_208, ok := item_158.(OptionSome[A]); ok {
			return func() []A {
				return sliceTailLoop[A](items, index+1, MygoIN5SliceM6Append(out, v_208.F0))
			}()
		} else {
			if _, ok := item_158.(OptionNone[A]); ok {
				return func() []A {
					return out
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func importPathForGo(path string) string {
	return strings.TrimPrefix(path, "go:")
}
func importAliasForPath(path string) string {
	cleanPath_159 := importPathForGo(path)
	if cleanPath_159 == "" {
		return ""
	}
	trimmed_160 := strings.TrimSuffix(cleanPath_159, "/")
	parts_161 := strings.Split(trimmed_160, "/")
	return toPackageName(MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(parts_161, MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(parts_161)-1), trimmed_160))
}
func toPackageName(name string) string {
	if name == "" {
		return "main"
	}
	return strings.ToLower(sanitizeIdent(name))
}
func exportName(name string) string {
	if name == "" {
		return name
	}
	first_162 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(name, 0, 1), "")
	rest_163 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(name, 1, MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(name)), "")
	return MygoIN6StringM7ToUpper(first_162) + rest_163
}
func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return 'a' - ('a' - 'A')
	}
	return r
}
func splitTypeArgs(typ string) TypeArgParts {
	clean_164 := strings.TrimSpace(typ)
	if clean_164 == "" {
		return TypeArgParts{Name: "", Args: []string([]string{})}
	}
	idx_165 := strings.Index(clean_164, "[")
	if idx_165 < 0 {
		return TypeArgParts{Name: clean_164, Args: []string([]string{})}
	}
	endPos_166 := matchingTypeArgEnd(clean_164, idx_165)
	if endPos_166 < 0 || endPos_166 < idx_165 {
		return TypeArgParts{Name: clean_164, Args: []string([]string{})}
	}
	name_167 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(clean_164, 0, idx_165), "")
	inner_168 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(clean_164, idx_165+1, endPos_166), "")
	if inner_168 == "" {
		return TypeArgParts{Name: name_167, Args: []string([]string{})}
	}
	return TypeArgParts{Name: name_167, Args: splitTopLevel(inner_168, ',')}
}
func matchingTypeArgEnd(typ string, open int) int {
	return func() int {
		depth := 0
		for i, r := range typ[open:] {
			switch r {
			case '[':
				depth++
			case ']':
				depth--
				if depth == 0 {
					return open + i
				}
			}
		}
		return -1
	}()
}
func splitTopLevel(s string, sep rune) []string {
	return func() []string {
		parts := []string{}
		depth := 0
		start := 0
		for i, r := range s {
			switch r {
			case '[', '(':
				depth++
			case ']', ')':
				if depth > 0 {
					depth--
				}
			default:
				if r == sep && depth == 0 {
					parts = append(parts, strings.TrimSpace(s[start:i]))
					start = i + len(string(r))
				}
			}
		}
		parts = append(parts, strings.TrimSpace(s[start:]))
		return parts
	}()
}
func isInherentReceiverParam(paramType ast2.TypeExpr, implType ast2.TypeExpr) bool {
	return typeString(paramType) == typeString(implType)
}
func typeString(t ast2.TypeExpr) string {
	return func() string {
		if v_210, ok := t.(ast2.TypeExprNamedType); ok {
			return func() string {
				if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_210.F1) == 0 {
					return v_210.F0
				}
				argStrs_171 := typeArgsToStrings(v_210.F1, MygoIN3SetM3New[string]())
				return v_210.F0 + "[" + joinStrings(argStrs_171, ", ") + "]"
			}()
		} else {
			if v_209, ok := t.(ast2.TypeExprFuncType); ok {
				return func() string {
					paramStrs_169 := typeExprsToStrings(v_209.F0, MygoIN3SetM3New[string]())
					retStr_170 := typeString(*v_209.F1)
					if retStr_170 == "" {
						return "func(" + joinStrings(paramStrs_169, ", ") + ")"
					}
					return "func(" + joinStrings(paramStrs_169, ", ") + ") " + retStr_170
				}()
			} else {
				return func() string {
					return "any"
				}()
			}
		}
	}()
}
