// Code generated by mygo; DO NOT EDIT.

package codegen2

import (
	"strconv"
	"strings"

	"github.com/mygo-lang/mygo/internal/mygo/ast2"
	. "github.com/mygo-lang/mygo/prelude"
)

type TypeArgParts struct {
	Name string
	Args []string
}

func goType(t ast2.TypeExpr, typeParams map[string]struct{}) string {
	var expr_754 string
	if v_289, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_753 string
		var expr_752 string
		if setContainsString(typeParams, v_289.F0) && MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_289.F1) == 0 {
			expr_752 = v_289.F0
		} else {
			var expr_751 string
			if isHKTConstructor(v_289.F0, v_289.F1, typeParams) {
				expr_751 = "HKT[" + v_289.F0 + ", " + hktApplicationArgs(v_289.F1, typeParams) + "]"
			} else {
				var expr_750 string
				fallback_749 := genericNamedType(v_289.F0, v_289.F1, typeParams)
				expr_750 = MygoIT11IEnumerableFN17OptionIEnumerableGN1AEGN6OptionGN1AEN1AEM4Fold(goPrimitiveType(v_289.F0), MygoIN6OptionM8UnwrapOr(goSpecialType(v_289.F0, v_289.F1, typeParams), fallback_749), func(_ string, mapped string) string {
					return mapped
				})
				expr_751 = expr_750
			}
			expr_752 = expr_751
		}
		expr_753 = expr_752
		expr_754 = expr_753
	} else {
		if v_288, ok := t.(ast2.TypeExprFuncType); ok {
			var expr_748 string
			paramStrs_746 := typeExprsToStrings(v_288.F0, typeParams)
			retStr_747 := goType(*v_288.F1, typeParams)
			if retStr_747 == "" || retStr_747 == "struct{}" {
				expr_748 = "func(" + joinStrings(paramStrs_746, ", ") + ")"
			}
			expr_748 = "func(" + joinStrings(paramStrs_746, ", ") + ") " + retStr_747
			expr_754 = expr_748
		} else {
			if v_287, ok := t.(ast2.TypeExprTupleType); ok {
				var expr_745 string
				if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_287.F0) == 0 {
					expr_745 = "struct{}"
				}
				parts_744 := tupleElemsToStrings(v_287.F0, typeParams)
				expr_745 = "struct { " + joinStrings(parts_744, "; ") + " }"
				expr_754 = expr_745
			} else {
				if _, ok := t.(ast2.TypeExprUnitType); ok {
					var expr_743 string
					expr_743 = "struct{}"
					expr_754 = expr_743
				} else {
					if v_285, ok := t.(ast2.TypeExprInlineGo); ok {
						var expr_742 string
						var expr_741 string
						if v_285.F1 == "" {
							var expr_739 string
							expr_739 = goType(*v_285.F0, typeParams)
							expr_741 = expr_739
						} else {
							var expr_740 string
							expr_740 = goType(*v_285.F0, typeParams)
							expr_741 = expr_740
						}
						expr_742 = expr_741
						expr_754 = expr_742
					} else {
						{
							var expr_738 string
							expr_738 = "any"
							expr_754 = expr_738
						}
					}
				}
			}
		}
	}
	return expr_754
}
func hktApplicationArgs(args []ast2.TypeExpr, typeParams map[string]struct{}) string {
	var expr_758 string
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		expr_758 = "any"
	} else {
		var expr_757 string
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
			expr_757 = goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams)
		} else {
			var expr_756 string
			first_755 := goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams)
			expr_756 = "HKT[" + first_755 + ", " + hktApplicationArgs(sliceDrop[ast2.TypeExpr](args, 1), typeParams) + "]"
			expr_757 = expr_756
		}
		expr_758 = expr_757
	}
	return expr_758
}
func isHKTConstructor(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) bool {
	var expr_759 bool
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		expr_759 = false
	} else {
		expr_759 = setContainsString(typeParams, name+"#hkt")
	}
	return expr_759
}
func genericNamedType(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) string {
	var expr_762 string
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		expr_762 = name
	} else {
		var expr_761 string
		argStrs_760 := typeArgsToStrings(args, typeParams)
		expr_761 = name + "[" + joinStrings(argStrs_760, ", ") + "]"
		expr_762 = expr_761
	}
	return expr_762
}
func goPrimitiveType(name string) Option[string] {
	var expr_782 Option[string]
	if name == "Int" {
		var expr_781 Option[string]
		expr_781 = Some[string]("int")
		expr_782 = expr_781
	} else {
		if name == "Int8" {
			var expr_780 Option[string]
			expr_780 = Some[string]("int8")
			expr_782 = expr_780
		} else {
			if name == "Int16" {
				var expr_779 Option[string]
				expr_779 = Some[string]("int16")
				expr_782 = expr_779
			} else {
				if name == "Int32" {
					var expr_778 Option[string]
					expr_778 = Some[string]("int32")
					expr_782 = expr_778
				} else {
					if name == "Int64" {
						var expr_777 Option[string]
						expr_777 = Some[string]("int64")
						expr_782 = expr_777
					} else {
						if name == "UInt" {
							var expr_776 Option[string]
							expr_776 = Some[string]("uint")
							expr_782 = expr_776
						} else {
							if name == "UInt8" {
								var expr_775 Option[string]
								expr_775 = Some[string]("uint8")
								expr_782 = expr_775
							} else {
								if name == "UInt16" {
									var expr_774 Option[string]
									expr_774 = Some[string]("uint16")
									expr_782 = expr_774
								} else {
									if name == "UInt32" {
										var expr_773 Option[string]
										expr_773 = Some[string]("uint32")
										expr_782 = expr_773
									} else {
										if name == "UInt64" {
											var expr_772 Option[string]
											expr_772 = Some[string]("uint64")
											expr_782 = expr_772
										} else {
											if name == "Byte" {
												var expr_771 Option[string]
												expr_771 = Some[string]("byte")
												expr_782 = expr_771
											} else {
												if name == "Rune" {
													var expr_770 Option[string]
													expr_770 = Some[string]("rune")
													expr_782 = expr_770
												} else {
													if name == "Float32" {
														var expr_769 Option[string]
														expr_769 = Some[string]("float32")
														expr_782 = expr_769
													} else {
														if name == "Float64" {
															var expr_768 Option[string]
															expr_768 = Some[string]("float64")
															expr_782 = expr_768
														} else {
															if name == "String" {
																var expr_767 Option[string]
																expr_767 = Some[string]("string")
																expr_782 = expr_767
															} else {
																if name == "Bool" {
																	var expr_766 Option[string]
																	expr_766 = Some[string]("bool")
																	expr_782 = expr_766
																} else {
																	if name == "Any" {
																		var expr_765 Option[string]
																		expr_765 = Some[string]("any")
																		expr_782 = expr_765
																	} else {
																		if name == "Unit" {
																			var expr_764 Option[string]
																			expr_764 = Some[string]("struct{}")
																			expr_782 = expr_764
																		} else {
																			{
																				var expr_763 Option[string]
																				expr_763 = None[string]()
																				expr_782 = expr_763
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_782
}
func goSpecialType(name string, args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	var expr_791 Option[string]
	if name == "Ref" {
		var expr_790 Option[string]
		expr_790 = unarySpecialType(args, typeParams, "*")
		expr_791 = expr_790
	} else {
		if name == "Slice" {
			var expr_789 Option[string]
			expr_789 = unarySpecialType(args, typeParams, "[]")
			expr_791 = expr_789
		} else {
			if name == "Map" {
				var expr_788 Option[string]
				expr_788 = mapSpecialType(args, typeParams)
				expr_791 = expr_788
			} else {
				if name == "Set" {
					var expr_787 Option[string]
					expr_787 = setSpecialType(args, typeParams)
					expr_791 = expr_787
				} else {
					if name == "Chan" {
						var expr_786 Option[string]
						expr_786 = unarySpecialType(args, typeParams, "chan ")
						expr_791 = expr_786
					} else {
						if name == "SendChan" {
							var expr_785 Option[string]
							expr_785 = unarySpecialType(args, typeParams, "chan<- ")
							expr_791 = expr_785
						} else {
							if name == "RecvChan" {
								var expr_784 Option[string]
								expr_784 = unarySpecialType(args, typeParams, "<-chan ")
								expr_791 = expr_784
							} else {
								{
									var expr_783 Option[string]
									expr_783 = None[string]()
									expr_791 = expr_783
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_791
}
func unarySpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}, prefix string) Option[string] {
	var expr_792 Option[string]
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
		expr_792 = Some[string](prefix + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams))
	} else {
		expr_792 = None[string]()
	}
	return expr_792
}
func mapSpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	var expr_793 Option[string]
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 2 {
		expr_793 = Some[string]("map[" + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams) + "]" + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 1), ast2.TypeExprUnitTypeCtor()), typeParams))
	} else {
		expr_793 = None[string]()
	}
	return expr_793
}
func setSpecialType(args []ast2.TypeExpr, typeParams map[string]struct{}) Option[string] {
	var expr_794 Option[string]
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 1 {
		expr_794 = Some[string]("map[" + goType(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor()), typeParams) + "]struct{}")
	} else {
		expr_794 = None[string]()
	}
	return expr_794
}
func goReturnType(t ast2.TypeExpr, typeParams map[string]struct{}) string {
	if isUnitType(t) {
		return ""
	}
	return goType(t, typeParams)
}
func goReturnTypes(t ast2.TypeExpr, typeParams map[string]struct{}) []string {
	var expr_799 []string
	if v_290, ok := t.(ast2.TypeExprTupleType); ok {
		var expr_798 []string
		expr_798 = MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(v_290.F0, func(item ast2.TypeExpr) string {
			return goType(item, typeParams)
		})
		expr_799 = expr_798
	} else {
		{
			var expr_797 []string
			rt_795 := goReturnType(t, typeParams)
			var expr_796 []string
			if rt_795 != "" {
				expr_796 = []string{rt_795}
			} else {
				expr_796 = []string([]string{})
			}
			expr_797 = expr_796
			expr_799 = expr_797
		}
	}
	return expr_799
}
func isUnitType(t ast2.TypeExpr) bool {
	var expr_804 bool
	if _, ok := t.(ast2.TypeExprUnitType); ok {
		var expr_803 bool
		expr_803 = true
		expr_804 = expr_803
	} else {
		if v_292, ok := t.(ast2.TypeExprTupleType); ok {
			var expr_802 bool
			expr_802 = MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_292.F0) == 0
			expr_804 = expr_802
		} else {
			if v_291, ok := t.(ast2.TypeExprNamedType); ok {
				var expr_801 bool
				expr_801 = v_291.F0 == "Unit" && MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_291.F1) == 0
				expr_804 = expr_801
			} else {
				{
					var expr_800 bool
					expr_800 = false
					expr_804 = expr_800
				}
			}
		}
	}
	return expr_804
}
func isUnitGoType(typ string) bool {
	trimmed_805 := strings.TrimSpace(typ)
	return trimmed_805 == "Unit" || trimmed_805 == "struct{}" || trimmed_805 == "()"
}
func setContainsString(items map[string]struct{}, target string) bool {
	return MygoIT11IEnumerableFN14SetIEnumerableGN1AEGN3SetGN1AEN1AEM4Fold(items, false, func(found bool, current string) bool {
		return found || current == target
	})
}
func typeParamSet(params []string) map[string]struct{} {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(params, MygoIN3SetM3New[string](), func(s map[string]struct{}, p string) map[string]struct{} {
		MygoIN3SetM3Add(s, p)
		var expr_806 map[string]struct{}
		if strings.HasPrefix(p, hktTypeParamName(p)+"[") {
			expr_806 = MygoIN3SetM3Add(s, hktTypeParamName(p)+"#hkt")
		} else {
			expr_806 = s
		}
		return expr_806
	})
}
func sanitizeIdent(s string) string {
	var result_807 string = func() string {
		var b strings.Builder
		for i, r := range s {
			if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
				if i == 0 && r >= '0' && r <= '9' {
					b.WriteRune('_')
				}
				b.WriteRune(r)
				continue
			}
			b.WriteRune('_')
		}
		return b.String()
	}()
	if MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(result_807) == 0 {
		return "_"
	}
	if isGoKeyword(result_807) {
		return result_807 + "_"
	}
	return result_807
}
func isGoKeyword(s string) bool {
	var expr_834 bool
	if s == "break" {
		var expr_833 bool
		expr_833 = true
		expr_834 = expr_833
	} else {
		if s == "case" {
			var expr_832 bool
			expr_832 = true
			expr_834 = expr_832
		} else {
			if s == "chan" {
				var expr_831 bool
				expr_831 = true
				expr_834 = expr_831
			} else {
				if s == "const" {
					var expr_830 bool
					expr_830 = true
					expr_834 = expr_830
				} else {
					if s == "continue" {
						var expr_829 bool
						expr_829 = true
						expr_834 = expr_829
					} else {
						if s == "default" {
							var expr_828 bool
							expr_828 = true
							expr_834 = expr_828
						} else {
							if s == "defer" {
								var expr_827 bool
								expr_827 = true
								expr_834 = expr_827
							} else {
								if s == "else" {
									var expr_826 bool
									expr_826 = true
									expr_834 = expr_826
								} else {
									if s == "fallthrough" {
										var expr_825 bool
										expr_825 = true
										expr_834 = expr_825
									} else {
										if s == "for" {
											var expr_824 bool
											expr_824 = true
											expr_834 = expr_824
										} else {
											if s == "func" {
												var expr_823 bool
												expr_823 = true
												expr_834 = expr_823
											} else {
												if s == "go" {
													var expr_822 bool
													expr_822 = true
													expr_834 = expr_822
												} else {
													if s == "goto" {
														var expr_821 bool
														expr_821 = true
														expr_834 = expr_821
													} else {
														if s == "if" {
															var expr_820 bool
															expr_820 = true
															expr_834 = expr_820
														} else {
															if s == "import" {
																var expr_819 bool
																expr_819 = true
																expr_834 = expr_819
															} else {
																if s == "interface" {
																	var expr_818 bool
																	expr_818 = true
																	expr_834 = expr_818
																} else {
																	if s == "map" {
																		var expr_817 bool
																		expr_817 = true
																		expr_834 = expr_817
																	} else {
																		if s == "package" {
																			var expr_816 bool
																			expr_816 = true
																			expr_834 = expr_816
																		} else {
																			if s == "range" {
																				var expr_815 bool
																				expr_815 = true
																				expr_834 = expr_815
																			} else {
																				if s == "return" {
																					var expr_814 bool
																					expr_814 = true
																					expr_834 = expr_814
																				} else {
																					if s == "select" {
																						var expr_813 bool
																						expr_813 = true
																						expr_834 = expr_813
																					} else {
																						if s == "struct" {
																							var expr_812 bool
																							expr_812 = true
																							expr_834 = expr_812
																						} else {
																							if s == "switch" {
																								var expr_811 bool
																								expr_811 = true
																								expr_834 = expr_811
																							} else {
																								if s == "type" {
																									var expr_810 bool
																									expr_810 = true
																									expr_834 = expr_810
																								} else {
																									if s == "var" {
																										var expr_809 bool
																										expr_809 = true
																										expr_834 = expr_809
																									} else {
																										{
																											var expr_808 bool
																											expr_808 = false
																											expr_834 = expr_808
																										}
																									}
																								}
																							}
																						}
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_834
}
func inherentReceiverName(t ast2.TypeExpr) string {
	var expr_837 string
	if v_294, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_836 string
		expr_836 = v_294.F0
		expr_837 = expr_836
	} else {
		{
			var expr_835 string
			expr_835 = ""
			expr_837 = expr_835
		}
	}
	return expr_837
}
func inherentMethodName(receiverName string, methodName string) string {
	return implMethodSymbol(mangleInherentImplSymbol(receiverName), methodName)
}
func variantGoTypeName(enumName string, variant string) string {
	if enumName == "" {
		return variant
	}
	return enumName + variant
}
func enumConstructorGoName(enumName string, variantName string) string {
	if (enumName == "Option" || enumName == "Result") && (variantName == "Some" || variantName == "None" || variantName == "Ok" || variantName == "Err") {
		return variantName
	}
	return variantNameForEnum(enumName, variantName) + "Ctor"
}
func variantNameForEnum(enumName string, variantName string) string {
	if enumName == "" {
		return variantName
	}
	return enumName + variantName
}
func helperFuncName(method string, typeKey string) string {
	cleaned_838 := strings.TrimPrefix(typeKey, "_")
	return implMethodSymbol(sanitizeIdent(cleaned_838), method)
}
func implMethodSymbol(implSymbol string, methodName string) string {
	return sanitizeIdent(implSymbol + "M" + mangleComponent(methodName))
}
func mangleInherentImplSymbol(receiverName string) string {
	return "MygoIN" + mangleComponent(receiverName)
}
func mangleInterfaceImplSymbol(ifaceName string, implType ast2.TypeExpr, args []ast2.TypeExpr) string {
	out_839 := "MygoIT" + mangleComponent(ifaceName) + "F" + mangleTypeExpr(implType) + "G"
	var i_840 int = 0
	for i_840 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) {
		out_839 = out_839 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, i_840), ast2.TypeExprUnitTypeCtor()))
		i_840 = i_840 + 1
	}
	return sanitizeIdent(out_839 + "E")
}
func mangleComponent(s string) string {
	clean_841 := sanitizeIdent(s)
	return strconv.Itoa(MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(clean_841)) + clean_841
}
func mangleTypeExpr(t ast2.TypeExpr) string {
	var expr_852 string
	if v_298, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_851 string
		out_849 := "N" + mangleComponent(canonicalMyGoTypeName(v_298.F0))
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_298.F1) > 0 {
			out_849 = out_849 + "G"
			var i_850 int = 0
			for i_850 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_298.F1) {
				out_849 = out_849 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_298.F1, i_850), ast2.TypeExprUnitTypeCtor()))
				i_850 = i_850 + 1
			}
			out_849 = out_849 + "E"
		}
		expr_851 = out_849
		expr_852 = expr_851
	} else {
		if v_297, ok := t.(ast2.TypeExprFuncType); ok {
			var expr_848 string
			out_846 := "F"
			var i_847 int = 0
			for i_847 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_297.F0) {
				out_846 = out_846 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_297.F0, i_847), ast2.TypeExprUnitTypeCtor()))
				i_847 = i_847 + 1
			}
			expr_848 = out_846 + "R" + mangleTypeExpr(*v_297.F1) + "E"
			expr_852 = expr_848
		} else {
			if v_296, ok := t.(ast2.TypeExprTupleType); ok {
				var expr_845 string
				out_843 := "U"
				var i_844 int = 0
				for i_844 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_296.F0) {
					out_843 = out_843 + mangleTypeExpr(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(v_296.F0, i_844), ast2.TypeExprUnitTypeCtor()))
					i_844 = i_844 + 1
				}
				expr_845 = out_843 + "E"
				expr_852 = expr_845
			} else {
				if _, ok := t.(ast2.TypeExprUnitType); ok {
					var expr_842 string
					expr_842 = "X" + mangleComponent("Unit")
					expr_852 = expr_842
				} else {
					panic("unreachable")
				}
			}
		}
	}
	return expr_852
}
func canonicalMyGoTypeName(name string) string {
	var expr_869 string
	if name == "int" {
		var expr_868 string
		expr_868 = "Int"
		expr_869 = expr_868
	} else {
		if name == "int8" {
			var expr_867 string
			expr_867 = "Int8"
			expr_869 = expr_867
		} else {
			if name == "uint8" {
				var expr_866 string
				expr_866 = "UInt8"
				expr_869 = expr_866
			} else {
				if name == "int16" {
					var expr_865 string
					expr_865 = "Int16"
					expr_869 = expr_865
				} else {
					if name == "uint16" {
						var expr_864 string
						expr_864 = "UInt16"
						expr_869 = expr_864
					} else {
						if name == "int32" {
							var expr_863 string
							expr_863 = "Int32"
							expr_869 = expr_863
						} else {
							if name == "uint32" {
								var expr_862 string
								expr_862 = "UInt32"
								expr_869 = expr_862
							} else {
								if name == "int64" {
									var expr_861 string
									expr_861 = "Int64"
									expr_869 = expr_861
								} else {
									if name == "uint" {
										var expr_860 string
										expr_860 = "UInt"
										expr_869 = expr_860
									} else {
										if name == "uint64" {
											var expr_859 string
											expr_859 = "UInt64"
											expr_869 = expr_859
										} else {
											if name == "float32" {
												var expr_858 string
												expr_858 = "Float32"
												expr_869 = expr_858
											} else {
												if name == "float64" {
													var expr_857 string
													expr_857 = "Float64"
													expr_869 = expr_857
												} else {
													if name == "string" {
														var expr_856 string
														expr_856 = "String"
														expr_869 = expr_856
													} else {
														if name == "bool" {
															var expr_855 string
															expr_855 = "Bool"
															expr_869 = expr_855
														} else {
															if name == "any" {
																var expr_854 string
																expr_854 = "Any"
																expr_869 = expr_854
															} else {
																{
																	var expr_853 string
																	expr_853 = name
																	expr_869 = expr_853
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return expr_869
}
func typeKeyFromType(typ string) string {
	step1_870 := strings.ReplaceAll(typ, "[", "_")
	step2_871 := strings.ReplaceAll(step1_870, "]", "")
	step3_872 := strings.ReplaceAll(step2_871, ", ", "_")
	step4_873 := strings.ReplaceAll(step3_872, ",", "_")
	step5_874 := strings.ReplaceAll(step4_873, " ", "")
	step6_875 := strings.ReplaceAll(step5_874, "*", "Ptr")
	step7_876 := strings.ReplaceAll(step6_875, ".", "_")
	step8_877 := strings.ReplaceAll(step7_876, "func(", "Func_")
	step9_878 := strings.ReplaceAll(step8_877, ")", "")
	return sanitizeIdent(strings.ToLower(step9_878))
}
func typeclassFuncType(paramTypes []string, retType string) string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(paramTypes) == 0 {
		if retType == "" {
			return "func()"
		}
		return "func() " + retType
	}
	var fn_879 string = "func(" + joinStrings(paramTypes, ", ") + ")"
	if retType != "" {
		fn_879 = fn_879 + " " + retType
	}
	return fn_879
}
func typeArgsToStrings(args []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(args) == 0 {
		return []string([]string{})
	}
	head_880 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(args, 0), ast2.TypeExprUnitTypeCtor())
	tail_881 := typeArgsToStrings(sliceDrop[ast2.TypeExpr](args, 1), typeParams)
	return MygoIN5SliceM7Prepend(tail_881, goType(head_880, typeParams))
}
func typeExprsToStrings(items []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return []string([]string{})
	}
	head_882 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), ast2.TypeExprUnitTypeCtor())
	tail_883 := typeExprsToStrings(sliceDrop[ast2.TypeExpr](items, 1), typeParams)
	return MygoIN5SliceM7Prepend(tail_883, goType(head_882, typeParams))
}
func tupleElemsToStrings(elems []ast2.TypeExpr, typeParams map[string]struct{}) []string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems) == 0 {
		return []string([]string{})
	}
	head_884 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(elems, 0), ast2.TypeExprUnitTypeCtor())
	tail_885 := tupleElemsToStrings(sliceDrop[ast2.TypeExpr](elems, 1), typeParams)
	i_886 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems) - MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(elems)
	return MygoIN5SliceM7Prepend(tail_885, "F"+MygoIT8ToStringFN3IntGN3IntEM8ToString(i_886)+" "+goType(head_884, typeParams))
}
func joinStrings(items []string, sep string) string {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return ""
	}
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 1 {
		return MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), "")
	}
	head_887 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), "")
	tail_888 := joinStrings(sliceDrop[string](items, 1), sep)
	return head_887 + sep + tail_888
}
func sliceDrop[A any](items []A, n int) []A {
	if n <= 0 {
		return items
	}
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		return items
	}
	return sliceDrop[A](sliceTail[A](items), n-1)
}
func sliceTail[A any](items []A) []A {
	return sliceTailLoop[A](items, 1, []A([]A{}))
}
func sliceTailLoop[A any](items []A, index int, out []A) []A {
	if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) {
		return out
	}
	item_889 := MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index)
	var expr_892 []A
	if v_300, ok := item_889.(OptionSome[A]); ok {
		var expr_891 []A
		expr_891 = sliceTailLoop[A](items, index+1, MygoIN5SliceM6Append(out, v_300.F0))
		expr_892 = expr_891
	} else {
		if _, ok := item_889.(OptionNone[A]); ok {
			var expr_890 []A
			expr_890 = out
			expr_892 = expr_890
		} else {
			panic("unreachable")
		}
	}
	return expr_892
}
func importPathForGo(path string) string {
	return strings.TrimPrefix(path, "go:")
}
func importAliasForPath(path string) string {
	cleanPath_893 := importPathForGo(path)
	if cleanPath_893 == "" {
		return ""
	}
	trimmed_894 := strings.TrimSuffix(cleanPath_893, "/")
	parts_895 := strings.Split(trimmed_894, "/")
	return toPackageName(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(parts_895, MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(parts_895)-1), trimmed_894))
}
func toPackageName(name string) string {
	if name == "" {
		return "main"
	}
	return strings.ToLower(sanitizeIdent(name))
}
func exportName(name string) string {
	if name == "" {
		return name
	}
	first_896 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(name, 0, 1), "")
	rest_897 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(name, 1, MygoIT11IEnumerableFN17StringIEnumerableGN6StringN4RuneEM3Len(name)), "")
	return MygoIN6StringM7ToUpper(first_896) + rest_897
}
func toUpper(r rune) rune {
	if r >= 'a' && r <= 'z' {
		return 'a' - ('a' - 'A')
	}
	return r
}
func splitTypeArgs(typ string) TypeArgParts {
	clean_898 := strings.TrimSpace(typ)
	if clean_898 == "" {
		return TypeArgParts{Name: "", Args: []string([]string{})}
	}
	idx_899 := strings.Index(clean_898, "[")
	if idx_899 < 0 {
		return TypeArgParts{Name: clean_898, Args: []string([]string{})}
	}
	endPos_900 := matchingTypeArgEnd(clean_898, idx_899)
	if endPos_900 < 0 || endPos_900 < idx_899 {
		return TypeArgParts{Name: clean_898, Args: []string([]string{})}
	}
	name_901 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(clean_898, 0, idx_899), "")
	inner_902 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(clean_898, idx_899+1, endPos_900), "")
	if inner_902 == "" {
		return TypeArgParts{Name: name_901, Args: []string([]string{})}
	}
	return TypeArgParts{Name: name_901, Args: splitTopLevel(inner_902, ',')}
}
func matchingTypeArgEnd(typ string, open int) int {
	return func() int {
		depth := 0
		for i, r := range typ[open:] {
			switch r {
			case '[':
				depth++
			case ']':
				depth--
				if depth == 0 {
					return open + i
				}
			}
		}
		return -1
	}()
}
func splitTopLevel(s string, sep rune) []string {
	return func() []string {
		parts := []string{}
		depth := 0
		start := 0
		for i, r := range s {
			switch r {
			case '[', '(':
				depth++
			case ']', ')':
				if depth > 0 {
					depth--
				}
			default:
				if r == sep && depth == 0 {
					parts = append(parts, strings.TrimSpace(s[start:i]))
					start = i + len(string(r))
				}
			}
		}
		parts = append(parts, strings.TrimSpace(s[start:]))
		return parts
	}()
}
func isInherentReceiverParam(paramType ast2.TypeExpr, implType ast2.TypeExpr) bool {
	return typeString(paramType) == typeString(implType)
}
func typeString(t ast2.TypeExpr) string {
	var expr_909 string
	if v_302, ok := t.(ast2.TypeExprNamedType); ok {
		var expr_908 string
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(v_302.F1) == 0 {
			expr_908 = v_302.F0
		}
		argStrs_907 := typeArgsToStrings(v_302.F1, MygoIN3SetM3New[string]())
		expr_908 = v_302.F0 + "[" + joinStrings(argStrs_907, ", ") + "]"
		expr_909 = expr_908
	} else {
		if v_301, ok := t.(ast2.TypeExprFuncType); ok {
			var expr_906 string
			paramStrs_904 := typeExprsToStrings(v_301.F0, MygoIN3SetM3New[string]())
			retStr_905 := typeString(*v_301.F1)
			if retStr_905 == "" {
				expr_906 = "func(" + joinStrings(paramStrs_904, ", ") + ")"
			}
			expr_906 = "func(" + joinStrings(paramStrs_904, ", ") + ") " + retStr_905
			expr_909 = expr_906
		} else {
			{
				var expr_903 string
				expr_903 = "any"
				expr_909 = expr_903
			}
		}
	}
	return expr_909
}
