// Code generated by mygo; DO NOT EDIT.

package prelude

import "fmt"

type Option[A any] interface {
	isOption()
}
type OptionSome[A any] struct {
	F0 A
}

func (_ OptionSome[A]) isOption() {}
func Some[A any](a0 A) Option[A] {
	return OptionSome[A]{F0: a0}
}

type OptionNone[A any] struct{}

func (_ OptionNone[A]) isOption() {}
func None[A any]() Option[A] {
	return OptionNone[A]{}
}

type Result[A any, E any] interface {
	isResult()
}
type ResultOk[A any, E any] struct {
	F0 A
}

func (_ ResultOk[A, E]) isResult() {}
func Ok[A any, E any](a0 A) Result[A, E] {
	return ResultOk[A, E]{F0: a0}
}

type ResultErr[A any, E any] struct {
	F0 E
}

func (_ ResultErr[A, E]) isResult() {}
func Err[A any, E any](a0 E) Result[A, E] {
	return ResultErr[A, E]{F0: a0}
}

type Show[A any] interface {
	show(value A) string
}
type Eq[A any] interface {
	equals(left A, right A) bool
}
type Enumerable[C any, A any] interface {
	each(c HKT[C, A], fn func(A)) struct{}
	filter(c HKT[C, A], fn func(A) bool) HKT[C, A]
	find(c HKT[C, A], fn func(A) bool) Option[*A]
	contains(c HKT[C, A], item A, eq Eq[A]) bool
}
type List[A any] struct {
	Head A
	Tail Option[*List[A]]
}
type IOption[A any] interface {
	isSome(self IOption[A]) bool
	isNone(self IOption[A]) bool
	unwrapOr(self IOption[A], defaultVal A) A
}
type HKTType interface{}
type HKT1[F any] interface{}
type HKT2[A any] interface{}
type HKT[F any, A any] interface{}

func show_int(value int) string {
	return fmt.Sprint(value)
}
func show_int64(value int64) string {
	return fmt.Sprint(value)
}
func show_float64(value float64) string {
	return fmt.Sprint(value)
}
func show_string(value string) string {
	return value
}
func show_bool(value bool) string {
	return fmt.Sprint(value)
}
func equals_int(left int, right int) bool {
	return left == right
}
func equals_int64(left int64, right int64) bool {
	return left == right
}
func equals_float64(left float64, right float64) bool {
	return left == right
}
func equals_string(left string, right string) bool {
	return left == right
}
func equals_bool(left bool, right bool) bool {
	return left == right
}
func each_list_t_t[T any](c List[T], fn func(T)) {
	{
		current_1 := &c
		done_2 := false
		for !done_2 {
			{
				fn(current_1.Head)
				if _, ok := current_1.Tail.(OptionNone[*List[T]]); ok {
					{
						done_2 = true
					}
				} else {
					if v, ok := current_1.Tail.(OptionSome[*List[T]]); ok {
						{
							current_1 = v.F0
						}
					}
				}
			}
		}
	}
	return
}
func map_list_t_t[T any, B any](c List[T], fn func(T) B) List[B] {
	panic("translate error")
}
func filter_list_t_t[T any](c List[T], fn func(T) bool) List[T] {
	panic("translate error")
}
func fold_list_t_t[T any, B any](c List[T], initial B, fn func(B, T) B) B {
	return func() B {
		acc_7 := initial
		done_8 := false
		current_9 := &c
		for !done_8 {
			{
				acc_7 = fn(acc_7, current_9.Head)
				if _, ok := current_9.Tail.(OptionNone[*List[T]]); ok {
					{
						done_8 = true
					}
				} else {
					if v, ok := current_9.Tail.(OptionSome[*List[T]]); ok {
						{
							current_9 = v.F0
						}
					}
				}
			}
		}
		return acc_7
	}()
}
func find_list_t_t[T any](c List[T], fn func(T) bool) Option[*T] {
	return func() Option[*T] {
		done_10 := false
		current_11 := &c
		for !done_10 {
			{
				if fn(current_11.Head) {
					{
						return Some[*T](&current_11.Head)
					}
				} else {
					{
						if _, ok := current_11.Tail.(OptionNone[*List[T]]); ok {
							{
								done_10 = true
							}
						} else {
							if v, ok := current_11.Tail.(OptionSome[*List[T]]); ok {
								{
									current_11 = v.F0
								}
							}
						}
					}
				}
			}
		}
		return None[T]()
	}()
}
func contains_list_t_t[T any](c List[T], item T, eq Eq[T]) bool {
	return func() bool {
		done_12 := false
		result_13 := false
		current_14 := &c
		for !done_12 {
			{
				if eq.equals(current_14.Head, item) {
					{
						result_13 = true
						done_12 = true
					}
				} else {
					{
						if _, ok := current_14.Tail.(OptionNone[*List[T]]); ok {
							{
								done_12 = true
							}
						} else {
							if v, ok := current_14.Tail.(OptionSome[*List[T]]); ok {
								{
									current_14 = v.F0
								}
							}
						}
					}
				}
			}
		}
		return result_13
	}()
}
func each__t_t[T any](c []T, fn func(T)) {
	for _, v := range c {
		fn(v)
	}

	return
}
func map__t_t[T any, B any](c []T, fn func(T) B) []B {
	return func() []B {
		out := make([]B, len(c))
		for i, v := range c {
			out[i] = fn(v)
		}
		return out
	}()

}
func filter__t_t[T any](c []T, fn func(T) bool) []T {
	return func() []T {
		out := make([]T, 0, len(c))
		for _, v := range c {
			if fn(v) {
				out = append(out, v)
			}
		}
		return out
	}()

}
func fold__t_t[T any, B any](c []T, initial B, fn func(B, T) B) B {
	return func() B {
		acc := initial
		for _, v := range c {
			acc = fn(acc, v)
		}
		return acc
	}()

}
func find__t_t[T any](c []T, fn func(T) bool) Option[*T] {
	return func() Option[*T] {
		for i := range c {
			if fn(c[i]) {
				return Some[*T](&c[i])
			}
		}
		return None[*T]()
	}()

}
func contains__t_t[T any](c []T, item T, eq Eq[T]) bool {
	return func() bool {
		for _, v := range c {
			if eq.equals(v, item) {
				return true
			}
		}
		return false
	}()

}
func each_map_kv_v[K comparable, V any](c map[K]V, fn func(V)) {
	for _, v := range c {
		fn(v)
	}

	return
}
func map_map_kv_v[K comparable, V any, B any](c map[K]V, fn func(V) B) map[K]B {
	return func() map[K]B {
		out := make(map[K]B, len(c))
		for k, v := range c {
			out[k] = fn(v)
		}
		return out
	}()

}
func filter_map_kv_v[K comparable, V any](c map[K]V, fn func(V) bool) map[K]V {
	return func() map[K]V {
		out := make(map[K]V, len(c))
		for k, v := range c {
			if fn(v) {
				out[k] = v
			}
		}
		return out
	}()

}
func fold_map_kv_v[K comparable, V any, B any](c map[K]V, initial B, fn func(B, V) B) B {
	return func() B {
		acc := initial
		for _, v := range c {
			acc = fn(acc, v)
		}
		return acc
	}()

}
func find_map_kv_v[K comparable, V any](c map[K]V, fn func(V) bool) Option[*V] {
	return func() Option[*V] {
		for _, v := range c {
			if fn(v) {
				val := v
				return Some[*V](&val)
			}
		}
		return None[*V]()
	}()

}
func each_map_astruct___a[A comparable](c map[A]struct{}, fn func(A)) {
	for v := range c {
		fn(v)
	}

	return
}
func map_map_astruct___a[A comparable, B comparable](c map[A]struct{}, fn func(A) B) map[B]struct{} {
	return func() map[B]struct{} {
		out := make(map[B]struct{}, len(c))
		for v := range c {
			out[fn(v)] = struct{}{}
		}
		return out
	}()

}
func filter_map_astruct___a[A comparable](c map[A]struct{}, fn func(A) bool) map[A]struct{} {
	return func() map[A]struct{} {
		out := make(map[A]struct{}, len(c))
		for v := range c {
			if fn(v) {
				out[v] = struct{}{}
			}
		}
		return out
	}()

}
func fold_map_astruct___a[A comparable, B comparable](c map[A]struct{}, initial B, fn func(B, A) B) B {
	return func() B {
		acc := initial
		for v := range c {
			acc = fn(acc, v)
		}
		return acc
	}()

}
func find_map_astruct___a[A comparable](c map[A]struct{}, fn func(A) bool) Option[*A] {
	return func() Option[*A] {
		for v := range c {
			if fn(v) {
				val := v
				return Some[*A](&val)
			}
		}
		return None[*A]()
	}()

}
func each_option_a_a[A any](c Option[A], fn func(A)) {
	panic("translate error")
}
func map_option_a_a[A any, B any](c Option[A], fn func(A) B) Option[B] {
	return func() Option[B] {
		if v, ok := c.(OptionSome[A]); ok {
			return func() Option[B] {
				return Some[B](fn(v.F0))
			}()
		} else {
			if _, ok := c.(OptionNone[A]); ok {
				return func() Option[B] {
					return None[B]()
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func filter_option_a_a[A any](c Option[A], fn func(A) bool) Option[A] {
	return func() Option[A] {
		if v, ok := c.(OptionSome[A]); ok {
			return func() Option[A] {
				return func() Option[A] {
					if fn(v.F0) {
						return Some[A](v.F0)
					} else {
						return None[A]()
					}
				}()
			}()
		} else {
			if _, ok := c.(OptionNone[A]); ok {
				return func() Option[A] {
					return None[A]()
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func fold_option_a_a[A any, B any](c Option[A], initial B, fn func(B, A) B) B {
	return func() B {
		if v, ok := c.(OptionSome[A]); ok {
			return func() B {
				return fn(initial, v.F0)
			}()
		} else {
			if _, ok := c.(OptionNone[A]); ok {
				return func() B {
					return initial
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func find_option_a_a[A any](c Option[A], fn func(A) bool) Option[*A] {
	return func() Option[*A] {
		if v, ok := c.(OptionSome[A]); ok {
			return func() Option[*A] {
				return func() Option[*A] {
					if fn(v.F0) {
						return Some[*A](&v.F0)
					} else {
						return None[A]()
					}
				}()
			}()
		} else {
			if _, ok := c.(OptionNone[A]); ok {
				return func() Option[*A] {
					return None[A]()
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func contains_option_a_a[A any](c Option[A], item A, eq Eq[A]) bool {
	return func() bool {
		if v, ok := c.(OptionSome[A]); ok {
			return func() bool {
				return eq.equals(v.F0, item)
			}()
		} else {
			if _, ok := c.(OptionNone[A]); ok {
				return func() bool {
					return false
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func isSome_a[A any](self Option[A]) bool {
	return func() bool {
		if _, ok := self.(OptionSome[A]); ok {
			return func() bool {
				return true
			}()
		} else {
			if _, ok := self.(OptionNone[A]); ok {
				return func() bool {
					return false
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func isNone_a[A any](self Option[A]) bool {
	return !isSome_a[A](self)
}
func unwrapOr_a[A any](opt Option[A], defaultVal A) A {
	return func() A {
		if v, ok := opt.(OptionSome[A]); ok {
			return func() A {
				return v.F0
			}()
		} else {
			if _, ok := opt.(OptionNone[A]); ok {
				return func() A {
					return defaultVal
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func typeKeyFromType(value string) string {
	return value
}
func optionFlatMap[A any, B any](opt Option[A], fn func(A) Option[B]) Option[B] {
	return func() Option[B] {
		if v, ok := opt.(OptionSome[A]); ok {
			return func() Option[B] {
				return fn(v.F0)
			}()
		} else {
			if _, ok := opt.(OptionNone[A]); ok {
				return func() Option[B] {
					return None[B]()
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultIsOk[A any, E any](res Result[A, E]) bool {
	return func() bool {
		if _, ok := res.(ResultOk[A, E]); ok {
			return func() bool {
				return true
			}()
		} else {
			if _, ok := res.(ResultErr[A, E]); ok {
				return func() bool {
					return false
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultIsErr[A any, E any](res Result[A, E]) bool {
	return func() bool {
		if _, ok := res.(ResultOk[A, E]); ok {
			return func() bool {
				return false
			}()
		} else {
			if _, ok := res.(ResultErr[A, E]); ok {
				return func() bool {
					return true
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultUnwrap[A any, E any](res Result[A, E], defaultVal A) A {
	return func() A {
		if v, ok := res.(ResultOk[A, E]); ok {
			return func() A {
				return v.F0
			}()
		} else {
			if _, ok := res.(ResultErr[A, E]); ok {
				return func() A {
					return defaultVal
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultMap[A any, B any, E any](res Result[A, E], fn func(A) B) Result[B, E] {
	return func() Result[B, E] {
		if v, ok := res.(ResultOk[A, E]); ok {
			return func() Result[B, E] {
				return Ok[B, E](fn(v.F0))
			}()
		} else {
			if v, ok := res.(ResultErr[A, E]); ok {
				return func() Result[B, E] {
					return Err[B, E](v.F0)
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultMapErr[A any, B any, E any](res Result[A, E], fn func(E) B) Result[A, B] {
	return func() Result[A, B] {
		if v, ok := res.(ResultOk[A, E]); ok {
			return func() Result[A, B] {
				return Ok[A, B](v.F0)
			}()
		} else {
			if v, ok := res.(ResultErr[A, E]); ok {
				return func() Result[A, B] {
					return Err[A, B](fn(v.F0))
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultAndThen[A any, B any, E any](res Result[A, E], fn func(A) Result[B, E]) Result[B, E] {
	return func() Result[B, E] {
		if v, ok := res.(ResultOk[A, E]); ok {
			return func() Result[B, E] {
				return fn(v.F0)
			}()
		} else {
			if v, ok := res.(ResultErr[A, E]); ok {
				return func() Result[B, E] {
					return Err[B, E](v.F0)
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
func resultOrElse[A any, E any](res Result[A, E], defaultVal A) A {
	return func() A {
		if v, ok := res.(ResultOk[A, E]); ok {
			return func() A {
				return v.F0
			}()
		} else {
			if _, ok := res.(ResultErr[A, E]); ok {
				return func() A {
					return defaultVal
				}()
			} else {
				panic("unreachable")
			}
		}
	}()
}
