// Code generated by mygo; DO NOT EDIT.

package prelude

func Each_map_astruct___a[A comparable](c map[A]struct{}, fn func(A)) {
	func() {
		for v := range c {
			fn(v)
		}
	}()
	return
}
func Len_map_astruct___a[A comparable](c map[A]struct{}) int {
	return len(c)
}
func Map_map_astruct___a[A comparable, B comparable](c map[A]struct{}, fn func(A) B) map[B]struct{} {
	return func() map[B]struct{} {
		out := make(map[B]struct{}, len(c))
		for v := range c {
			out[fn(v)] = struct{}{}
		}
		return out
	}()
}
func Filter_map_astruct___a[A comparable](c map[A]struct{}, fn func(A) bool) map[A]struct{} {
	return func() map[A]struct{} {
		out := make(map[A]struct{}, len(c))
		for v := range c {
			if fn(v) {
				out[v] = struct{}{}
			}
		}
		return out
	}()
}
func Fold_map_astruct___a[A comparable, B any](c map[A]struct{}, initial B, fn func(B, A) B) B {
	return func() B {
		acc := initial
		for v := range c {
			acc = fn(acc, v)
		}
		return acc
	}()
}
func Find_map_astruct___a[A comparable](c map[A]struct{}, fn func(A) bool) Option[*A] {
	return func() Option[*A] {
		for v := range c {
			if fn(v) {
				val := v
				return Some[*A](&val)
			}
		}
		return None[*A]()
	}()
}
func Contains_map_astruct___a[A comparable](c map[A]struct{}, item A, EqualsFn func(A, A) bool) bool {
	return func() bool {
		_, ok := c[item]
		return ok
	}()
}
func Set_New[A comparable]() map[A]struct{} {
	return func() map[A]struct{} {
		return make(map[A]struct{})
	}()
}
func Set_Add[A comparable](items map[A]struct{}, item A) map[A]struct{} {
	return func() map[A]struct{} {
		items[item] = struct{}{}
		return items
	}()
}
func Set_Delete[A comparable](items map[A]struct{}, item A) map[A]struct{} {
	return func() map[A]struct{} {
		delete(items, item)
		return items
	}()
}
