// Code generated by mygo; DO NOT EDIT.

package main

import "fmt"
import . "github.com/mygo-lang/mygo/prelude"

type Color interface {
	isColor()
}
type Color__Red struct {
}

func (Color__Red) isColor() {
}
func Color__Red__Ctor() Color {
	return Color__Red{}
}

type Color__Green struct {
}

func (Color__Green) isColor() {
}
func Color__Green__Ctor() Color {
	return Color__Green{}
}

type Color__Blue struct {
}

func (Color__Blue) isColor() {
}
func Color__Blue__Ctor() Color {
	return Color__Blue{}
}

type Point2D interface {
	isPoint2D()
}
type Point2D__Empty struct {
}

func (Point2D__Empty) isPoint2D() {
}
func Point2D__Empty__Ctor() Point2D {
	return Point2D__Empty{}
}

type Point2D__WithX struct {
	F0 int
}

func (Point2D__WithX) isPoint2D() {
}
func Point2D__WithX__Ctor(v0 int) Point2D {
	return Point2D__WithX{F0: v0}
}

type Point2D__WithY struct {
	F0 int
}

func (Point2D__WithY) isPoint2D() {
}
func Point2D__WithY__Ctor(v0 int) Point2D {
	return Point2D__WithY{F0: v0}
}

type Operation interface {
	isOperation()
}
type Operation__Add struct {
}

func (Operation__Add) isOperation() {
}
func Operation__Add__Ctor() Operation {
	return Operation__Add{}
}

type Operation__Subtract struct {
}

func (Operation__Subtract) isOperation() {
}
func Operation__Subtract__Ctor() Operation {
	return Operation__Subtract{}
}

type Operation__Multiply struct {
}

func (Operation__Multiply) isOperation() {
}
func Operation__Multiply__Ctor() Operation {
	return Operation__Multiply{}
}

type Person struct {
	name string
	age  int
}
type Rectangle struct {
	width  float64
	height float64
}
type Pair[T any] struct {
	first  T
	second T
}
type ColorTuple struct {
}
type Address struct {
	street string
	city   string
}
type Contact struct {
	name string
	Address
}

func area(rect Rectangle) float64 {
	return rect.width * rect.height
}
func swapPair[T any](p Pair[T]) Pair[T] {
	return Pair[T]{first: p.second, second: p.first}
}
func describeColor(color Color) string {
	var __mygo_expr_0 string
	if _, ok := color.(Color__Red); ok {
		__mygo_expr_0 = "red"
	} else {
		if _, ok := color.(Color__Green); ok {
			__mygo_expr_0 = "green"
		} else {
			if _, ok := color.(Color__Blue); ok {
				__mygo_expr_0 = "blue"
			} else {
			}
		}
	}
	return __mygo_expr_0
}
func maxInt(a int, b int) int {
	if a > b {
		return a
	} else {
		return b
	}
}
func describeOption[A any](value Option[A], ToStringFn func(A) string) string {
	var __mygo_expr_0 string
	if _, ok := value.(Option__None[A]); ok {
		__mygo_expr_0 = "None"
	} else {
		if __mygo_match___mygo_expr_1, ok := value.(Option__Some[A]); ok {
			__mygo_expr_0 = "Some(" + ToStringFn(__mygo_match___mygo_expr_1.F0) + ")"
		} else {
		}
	}
	return __mygo_expr_0
}
func buildList() List[int] {
	var noneTail Option[List[int]] = None[List[int]]()
	lastNode := MygoIN4ListM4Cons[int](3, noneTail)
	middleNode := MygoIN4ListM4Cons[int](2, Some[List[int]](lastNode))
	return MygoIN4ListM4Cons[int](1, Some[List[int]](middleNode))
}
func sumList(lst List[int]) int {
	var total int = 0
	var current List[int] = lst
	var done bool = false
	for !done {
		headVal := MygoIN4ListM4Head(current)
		total = total + headVal
		__mygo_expr_0 := MygoIN4ListM4Tail(current)
		if _, ok := __mygo_expr_0.(Option__None[List[int]]); ok {
			done = true
		} else {
			if __mygo_match___mygo_expr_1, ok := __mygo_expr_0.(Option__Some[List[int]]); ok {
				current = __mygo_match___mygo_expr_1.F0
			} else {
			}
		}
	}
	return total
}
func demo() string {
	red := Color__Red__Ctor()
	point := Point2D__WithY__Ctor(20)
	op := Operation__Multiply__Ctor()
	var empty Option[float64] = None[float64]()
	var someVal Option[int] = Some[int](42)
	person := Person{name: "Charlie", age: 25}
	rect := Rectangle{width: 10.0, height: 5.0}
	pair := Pair[int]{first: 1, second: 2}
	color := ColorTuple{}
	addr := Address{street: "Main St", city: "NYC"}
	contact := Contact{name: "Bob"}
	areaValue := area(rect)
	swapped := swapPair(pair)
	bigger := maxInt(3, 5)
	colorText := describeColor(Color__Green__Ctor())
	lst := buildList()
	sum := sumList(lst)
	var summary string = fmt.Sprintf("red=%v point=%v op=%v empty=%v some=%v person=%v rect=%v pair=%v color=%v addr=%v contact=%v area=%v swapped=%v bigger=%v colorText=%v sum=%v", red, point, op, describeOption(empty, MygoIT8ToStringFN4BoolGN4BoolEM8ToString), describeOption(someVal, MygoIT8ToStringFN4BoolGN4BoolEM8ToString), person, rect, pair, color, addr, contact, areaValue, swapped, bigger, colorText, sum)
	fmt.Println(summary)
	return summary
}
func main() {
	fmt.Println(demo())
	return
}
