// Code generated by mygo; DO NOT EDIT.

package typeinference2

import (
	"strings"

	"github.com/mygo-lang/mygo/internal/mygo/ast2"
	. "github.com/mygo-lang/mygo/prelude"
)

type MonoType interface {
	isMonoType()
}
type MonoTypeTVar struct {
	F0 int
}

func (_ MonoTypeTVar) isMonoType() {
}
func MonoTypeTVarCtor(a0 int) MonoType {
	return MonoTypeTVar{F0: a0}
}

type MonoTypeTKVar struct {
	F0 int
}

func (_ MonoTypeTKVar) isMonoType() {
}
func MonoTypeTKVarCtor(a0 int) MonoType {
	return MonoTypeTKVar{F0: a0}
}

type MonoTypeTCon struct {
	F0 string
	F1 []MonoType
}

func (_ MonoTypeTCon) isMonoType() {
}
func MonoTypeTConCtor(a0 string, a1 []MonoType) MonoType {
	return MonoTypeTCon{F0: a0, F1: a1}
}

type MonoTypeTFunc struct {
	F0 []MonoType
	F1 *MonoType
}

func (_ MonoTypeTFunc) isMonoType() {
}
func MonoTypeTFuncCtor(a0 []MonoType, a1 *MonoType) MonoType {
	return MonoTypeTFunc{F0: a0, F1: a1}
}

type MonoTypeTTuple struct {
	F0 []MonoType
}

func (_ MonoTypeTTuple) isMonoType() {
}
func MonoTypeTTupleCtor(a0 []MonoType) MonoType {
	return MonoTypeTTuple{F0: a0}
}

type MonoTypeTUnit struct {
}

func (_ MonoTypeTUnit) isMonoType() {
}
func MonoTypeTUnitCtor() MonoType {
	return MonoTypeTUnit{}
}

type MonoTypeTGoPackage struct {
	F0 string
}

func (_ MonoTypeTGoPackage) isMonoType() {
}
func MonoTypeTGoPackageCtor(a0 string) MonoType {
	return MonoTypeTGoPackage{F0: a0}
}

type Scheme struct {
	Bound      []int
	Predicates []Predicate
	Body       MonoType
}
type Predicate struct {
	ClassName string
	Args      []MonoType
}
type QualifiedType struct {
	Predicates []Predicate
	Body       MonoType
}
type EnvEntry struct {
	Name   string
	Scheme Scheme
}
type FieldEntry struct {
	TypeName  string
	FieldName string
	Type      MonoType
}
type SubstEntry struct {
	ID   int
	Type MonoType
}
type InferState struct {
	FreshVarID int
}
type InferResult struct {
	Type       MonoType
	Predicates []Predicate
	Subst      []SubstEntry
	State      InferState
}
type PackageInfo struct {
	Env        []EnvEntry
	Fields     []FieldEntry
	GoPackages []GoPackageEntry
}
type GoPackageEntry struct {
	Alias string
	Path  string
}
type DeclInfer struct {
	Env    []EnvEntry
	Fields []FieldEntry
	State  InferState
}
type ArgsResult struct {
	Types      []MonoType
	Predicates []Predicate
	Subst      []SubstEntry
	State      InferState
}
type BlockInferStep struct {
	Result InferResult
	Env    []EnvEntry
}
type PkgDecls struct {
	Decls []ast2.Decl
}
type PkgDeclSource struct {
	Path  string
	Decls []ast2.Decl
}

func NewInferState() InferState {
	return InferState{FreshVarID: 1}
}
func InferFile(file ast2.File) Result[PackageInfo, string] {
	env_461 := predeclareFunctions(file.Decls, initialEnv())
	goPkgImports_462 := collectGoPackageImports(file.Decls)
	envWithGoPkgs_463 := seedGoPackageEnv(goPkgImports_462, env_461)
	var expr_466 Result[PackageInfo, string]
	if v_196, ok := inferDecls(file.Decls, envWithGoPkgs_463, []FieldEntry{}, NewInferState()).(ResultOk[PackageInfo, string]); ok {
		var expr_465 Result[PackageInfo, string]
		expr_465 = Ok[PackageInfo, string](PackageInfo{Env: v_196.F0.Env, Fields: v_196.F0.Fields, GoPackages: goPkgImports_462})
		expr_466 = expr_465
	} else {
		if v_195, ok := inferDecls(file.Decls, envWithGoPkgs_463, []FieldEntry{}, NewInferState()).(ResultErr[PackageInfo, string]); ok {
			var expr_464 Result[PackageInfo, string]
			expr_464 = Err[PackageInfo, string](v_195.F0)
			expr_466 = expr_464
		} else {
			panic("unreachable")
		}
	}
	return expr_466
}
func InferPackage(files []PkgDeclSource) Result[PackageInfo, string] {
	allDecls_467 := flattenPkgDecls(files, 0, []ast2.Decl([]ast2.Decl{}))
	predeclEnv_468 := predeclareAllFunctions(allDecls_467, initialEnv())
	goPkgImports_469 := collectGoPackageImports(allDecls_467)
	envWithGoPkgs_470 := seedGoPackageEnv(goPkgImports_469, predeclEnv_468)
	result_471 := inferDecls(allDecls_467, envWithGoPkgs_470, []FieldEntry{}, NewInferState())
	var expr_474 Result[PackageInfo, string]
	if v_198, ok := result_471.(ResultOk[PackageInfo, string]); ok {
		var expr_473 Result[PackageInfo, string]
		expr_473 = Ok[PackageInfo, string](PackageInfo{Env: v_198.F0.Env, Fields: v_198.F0.Fields, GoPackages: goPkgImports_469})
		expr_474 = expr_473
	} else {
		if v_197, ok := result_471.(ResultErr[PackageInfo, string]); ok {
			var expr_472 Result[PackageInfo, string]
			expr_472 = Err[PackageInfo, string](v_197.F0)
			expr_474 = expr_472
		} else {
			panic("unreachable")
		}
	}
	return expr_474
}
func collectGoPackageImports(decls []ast2.Decl) []GoPackageEntry {
	return MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(decls, []GoPackageEntry([]GoPackageEntry{}), func(out []GoPackageEntry, d ast2.Decl) []GoPackageEntry {
		var expr_482 []GoPackageEntry
		if v_199, ok := d.(ast2.DeclImportDecl); ok {
			var expr_481 []GoPackageEntry
			var expr_480 []GoPackageEntry
			if strings.HasPrefix(v_199.F1, "go:") {
				var expr_479 []GoPackageEntry
				cleanPath_476 := strings.TrimPrefix(v_199.F1, "go:")
				existing_477 := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(out, false, func(found bool, e GoPackageEntry) bool {
					return found || e.Alias == v_199.F0
				})
				var expr_478 []GoPackageEntry
				if existing_477 {
					expr_478 = out
				} else {
					expr_478 = MygoIN5SliceM6Append(out, GoPackageEntry{Alias: v_199.F0, Path: cleanPath_476})
				}
				expr_479 = expr_478
				expr_480 = expr_479
			} else {
				expr_480 = out
			}
			expr_481 = expr_480
			expr_482 = expr_481
		} else {
			{
				var expr_475 []GoPackageEntry
				expr_475 = out
				expr_482 = expr_475
			}
		}
		return expr_482
	})
}
func seedGoPackageEnv(goPkgs []GoPackageEntry, env []EnvEntry) []EnvEntry {
	var expr_485 []EnvEntry
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(goPkgs) == 0 {
		expr_485 = env
	} else {
		var expr_484 []EnvEntry
		pkg_483 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(goPkgs, 0), GoPackageEntry{Alias: "", Path: ""})
		expr_484 = seedGoPackageEnv(sliceDrop[GoPackageEntry](goPkgs, 1), envPut(env, pkg_483.Alias, Scheme{Bound: []int{}, Predicates: []Predicate{}, Body: MonoTypeTGoPackageCtor(pkg_483.Alias)}))
		expr_485 = expr_484
	}
	return expr_485
}
func flattenPkgDecls(files []PkgDeclSource, index int, out []ast2.Decl) []ast2.Decl {
	var expr_488 []ast2.Decl
	if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(files) {
		expr_488 = out
	} else {
		var expr_487 []ast2.Decl
		f_486 := MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(files, index), PkgDeclSource{Path: "", Decls: []ast2.Decl([]ast2.Decl{})})
		expr_487 = flattenPkgDecls(files, index+1, appendDecls(out, f_486.Decls))
		expr_488 = expr_487
	}
	return expr_488
}
func predeclareAllFunctions(decls []ast2.Decl, env []EnvEntry) []EnvEntry {
	return predeclareFunctions(decls, env)
}
func appendDecls(acc []ast2.Decl, items []ast2.Decl) []ast2.Decl {
	var expr_489 []ast2.Decl
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		expr_489 = acc
	} else {
		expr_489 = appendDecls(MygoIN5SliceM6Append(acc, MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), ast2.DeclImportDeclCtor("", ""))), sliceDrop[ast2.Decl](items, 1))
	}
	return expr_489
}
