// Code generated by mygo; DO NOT EDIT.

package typeinference2

import (
	"github.com/mygo-lang/mygo/internal/mygo/ast2"
	. "github.com/mygo-lang/mygo/prelude"
)

func monoEqual(a MonoType, b MonoType) bool {
	var expr_585 bool
	if v_248, ok := a.(MonoTypeTVar); ok {
		var expr_584 bool
		var expr_583 bool
		if v_249, ok := b.(MonoTypeTVar); ok {
			var expr_582 bool
			expr_582 = v_248.F0 == v_249.F0
			expr_583 = expr_582
		} else {
			{
				var expr_581 bool
				expr_581 = false
				expr_583 = expr_581
			}
		}
		expr_584 = expr_583
		expr_585 = expr_584
	} else {
		if v_246, ok := a.(MonoTypeTKVar); ok {
			var expr_580 bool
			var expr_579 bool
			if v_247, ok := b.(MonoTypeTKVar); ok {
				var expr_578 bool
				expr_578 = v_246.F0 == v_247.F0
				expr_579 = expr_578
			} else {
				{
					var expr_577 bool
					expr_577 = false
					expr_579 = expr_577
				}
			}
			expr_580 = expr_579
			expr_585 = expr_580
		} else {
			if v_244, ok := a.(MonoTypeTCon); ok {
				var expr_576 bool
				var expr_575 bool
				if v_245, ok := b.(MonoTypeTCon); ok {
					var expr_574 bool
					expr_574 = v_244.F0 == v_245.F0 && monoListEqual(v_244.F1, v_245.F1)
					expr_575 = expr_574
				} else {
					{
						var expr_573 bool
						expr_573 = false
						expr_575 = expr_573
					}
				}
				expr_576 = expr_575
				expr_585 = expr_576
			} else {
				if v_242, ok := a.(MonoTypeTFunc); ok {
					var expr_572 bool
					var expr_571 bool
					if v_243, ok := b.(MonoTypeTFunc); ok {
						var expr_570 bool
						expr_570 = monoListEqual(v_242.F0, v_243.F0) && monoEqual(*v_242.F1, *v_243.F1)
						expr_571 = expr_570
					} else {
						{
							var expr_569 bool
							expr_569 = false
							expr_571 = expr_569
						}
					}
					expr_572 = expr_571
					expr_585 = expr_572
				} else {
					if v_240, ok := a.(MonoTypeTTuple); ok {
						var expr_568 bool
						var expr_567 bool
						if v_241, ok := b.(MonoTypeTTuple); ok {
							var expr_566 bool
							expr_566 = monoListEqual(v_240.F0, v_241.F0)
							expr_567 = expr_566
						} else {
							{
								var expr_565 bool
								expr_565 = false
								expr_567 = expr_565
							}
						}
						expr_568 = expr_567
						expr_585 = expr_568
					} else {
						if _, ok := a.(MonoTypeTUnit); ok {
							var expr_564 bool
							var expr_563 bool
							if _, ok := b.(MonoTypeTUnit); ok {
								var expr_562 bool
								expr_562 = true
								expr_563 = expr_562
							} else {
								{
									var expr_561 bool
									expr_561 = false
									expr_563 = expr_561
								}
							}
							expr_564 = expr_563
							expr_585 = expr_564
						} else {
							if v_236, ok := a.(MonoTypeTGoPackage); ok {
								var expr_560 bool
								var expr_559 bool
								if v_237, ok := b.(MonoTypeTGoPackage); ok {
									var expr_558 bool
									expr_558 = v_236.F0 == v_237.F0
									expr_559 = expr_558
								} else {
									{
										var expr_557 bool
										expr_557 = false
										expr_559 = expr_557
									}
								}
								expr_560 = expr_559
								expr_585 = expr_560
							} else {
								panic("unreachable")
							}
						}
					}
				}
			}
		}
	}
	return expr_585
}
func monoListEqual(a []MonoType, b []MonoType) bool {
	var expr_587 bool
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(a) != MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(b) {
		expr_587 = false
	} else {
		var expr_586 bool
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(a) == 0 {
			expr_586 = true
		} else {
			expr_586 = monoEqual(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(a, 0), MonoTypeTUnitCtor()), MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(b, 0), MonoTypeTUnitCtor())) && monoListEqual(sliceDrop[MonoType](a, 1), sliceDrop[MonoType](b, 1))
		}
		expr_587 = expr_586
	}
	return expr_587
}
func monoString(t MonoType) string {
	var expr_595 string
	if v_256, ok := t.(MonoTypeTVar); ok {
		var expr_594 string
		expr_594 = "t" + MygoIT8ToStringFN3IntGN3IntEM8ToString(v_256.F0)
		expr_595 = expr_594
	} else {
		if v_255, ok := t.(MonoTypeTKVar); ok {
			var expr_593 string
			expr_593 = "K" + MygoIT8ToStringFN3IntGN3IntEM8ToString(v_255.F0)
			expr_595 = expr_593
		} else {
			if v_254, ok := t.(MonoTypeTCon); ok {
				var expr_592 string
				expr_592 = v_254.F0
				expr_595 = expr_592
			} else {
				if _, ok := t.(MonoTypeTFunc); ok {
					var expr_591 string
					expr_591 = "func"
					expr_595 = expr_591
				} else {
					if _, ok := t.(MonoTypeTTuple); ok {
						var expr_590 string
						expr_590 = "tuple"
						expr_595 = expr_590
					} else {
						if _, ok := t.(MonoTypeTUnit); ok {
							var expr_589 string
							expr_589 = "()"
							expr_595 = expr_589
						} else {
							if v_250, ok := t.(MonoTypeTGoPackage); ok {
								var expr_588 string
								expr_588 = "go package " + v_250.F0
								expr_595 = expr_588
							} else {
								panic("unreachable")
							}
						}
					}
				}
			}
		}
	}
	return expr_595
}
func instantiate(scheme Scheme, state InferState) MonoType {
	return instantiateBound(scheme.Bound, scheme.Body, state, []SubstEntry{})
}
func instantiateBound(bound []int, body MonoType, state InferState, subst []SubstEntry) MonoType {
	var expr_598 MonoType
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(bound) == 0 {
		expr_598 = applySubst(subst, body)
	} else {
		var expr_597 MonoType
		id_596 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(bound, 0), 0)
		expr_597 = instantiateBound(sliceDrop[int](bound, 1), body, InferState{FreshVarID: state.FreshVarID + 1}, MygoIN5SliceM7Prepend(subst, SubstEntry{ID: id_596, Type: MonoTypeTVarCtor(state.FreshVarID)}))
		expr_598 = expr_597
	}
	return expr_598
}
func freeVars(t MonoType, out []int) []int {
	var expr_608 []int
	if v_263, ok := t.(MonoTypeTVar); ok {
		var expr_607 []int
		var expr_606 []int
		if containsInt(out, v_263.F0) {
			expr_606 = out
		} else {
			expr_606 = MygoIN5SliceM6Append(out, v_263.F0)
		}
		expr_607 = expr_606
		expr_608 = expr_607
	} else {
		if v_262, ok := t.(MonoTypeTKVar); ok {
			var expr_605 []int
			var expr_604 []int
			if containsInt(out, v_262.F0) {
				expr_604 = out
			} else {
				expr_604 = MygoIN5SliceM6Append(out, v_262.F0)
			}
			expr_605 = expr_604
			expr_608 = expr_605
		} else {
			if v_261, ok := t.(MonoTypeTCon); ok {
				var expr_603 []int
				expr_603 = freeVarsAll(v_261.F1, out)
				expr_608 = expr_603
			} else {
				if v_260, ok := t.(MonoTypeTFunc); ok {
					var expr_602 []int
					expr_602 = freeVarsAll(v_260.F0, freeVars(*v_260.F1, out))
					expr_608 = expr_602
				} else {
					if v_259, ok := t.(MonoTypeTTuple); ok {
						var expr_601 []int
						expr_601 = freeVarsAll(v_259.F0, out)
						expr_608 = expr_601
					} else {
						if _, ok := t.(MonoTypeTUnit); ok {
							var expr_600 []int
							expr_600 = out
							expr_608 = expr_600
						} else {
							if _, ok := t.(MonoTypeTGoPackage); ok {
								var expr_599 []int
								expr_599 = out
								expr_608 = expr_599
							} else {
								panic("unreachable")
							}
						}
					}
				}
			}
		}
	}
	return expr_608
}
func freeVarsAll(items []MonoType, out []int) []int {
	var expr_609 []int
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		expr_609 = out
	} else {
		expr_609 = freeVarsAll(sliceDrop[MonoType](items, 1), freeVars(MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), MonoTypeTUnitCtor()), out))
	}
	return expr_609
}
func containsInt(items []int, value int) bool {
	var expr_610 bool
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		expr_610 = false
	} else {
		expr_610 = MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), 0) == value || containsInt(sliceDrop[int](items, 1), value)
	}
	return expr_610
}
func envFreeVars(env []EnvEntry, out []int) []int {
	var expr_615 []int
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(env) == 0 {
		expr_615 = out
	} else {
		var expr_614 []int
		item_611 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(env, 0), EnvEntry{Name: "", Scheme: Scheme{Bound: []int{}, Predicates: []Predicate{}, Body: MonoTypeTUnitCtor()}})
		bodyVars_612 := freeVars(item_611.Scheme.Body, out)
		predicateVars_613 := freeVarsPredicates(item_611.Scheme.Predicates, bodyVars_612)
		expr_614 = envFreeVars(sliceDrop[EnvEntry](env, 1), removeInts(predicateVars_613, item_611.Scheme.Bound))
		expr_615 = expr_614
	}
	return expr_615
}
func freeVarsPredicates(items []Predicate, out []int) []int {
	var expr_618 []int
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		expr_618 = out
	} else {
		var expr_617 []int
		predicate_616 := MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), Predicate{ClassName: "", Args: []MonoType([]MonoType{})})
		expr_617 = freeVarsPredicates(sliceDrop[Predicate](items, 1), freeVarsAll(predicate_616.Args, out))
		expr_618 = expr_617
	}
	return expr_618
}
func removeInts(items []int, removed []int) []int {
	var expr_622 []int
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
		expr_622 = []int{}
	} else {
		var expr_621 []int
		tail_619 := removeInts(sliceDrop[int](items, 1), removed)
		var expr_620 []int
		if containsInt(removed, MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), 0)) {
			expr_620 = tail_619
		} else {
			expr_620 = MygoIN5SliceM7Prepend(tail_619, MygoIN6OptionM8UnwrapOr(MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, 0), 0))
		}
		expr_621 = expr_620
		expr_622 = expr_621
	}
	return expr_622
}
func generalize(env []EnvEntry, t MonoType) []int {
	return removeInts(freeVars(t, []int{}), envFreeVars(env, []int{}))
}
func isArithmetic(op string) bool {
	return op == "+" || op == "-" || op == "*" || op == "/"
}
func isComparison(op string) bool {
	return op == "==" || op == "!=" || op == "<" || op == ">" || op == "<=" || op == ">="
}
func emptyMonoTypes() []MonoType {
	return []MonoType{}
}
func emptyASTTypeExprs() []ast2.TypeExpr {
	return []ast2.TypeExpr{}
}
func sliceDrop[A any](items []A, n int) []A {
	var expr_624 []A
	if n <= 0 {
		expr_624 = items
	} else {
		var expr_623 []A
		if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) == 0 {
			expr_623 = []A{}
		} else {
			expr_623 = sliceDrop[A](sliceTail[A](items), n-1)
		}
		expr_624 = expr_623
	}
	return expr_624
}
func sliceTail[A any](items []A) []A {
	return sliceTailLoop[A](items, 1, []A([]A{}))
}
func sliceTailLoop[A any](items []A, index int, out []A) []A {
	var expr_628 []A
	if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) {
		expr_628 = out
	} else {
		var expr_627 []A
		if v_265, ok := MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index).(OptionSome[A]); ok {
			var expr_626 []A
			expr_626 = sliceTailLoop[A](items, index+1, MygoIN5SliceM6Append(out, v_265.F0))
			expr_627 = expr_626
		} else {
			if _, ok := MygoIT11IAssignableFN5SliceGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index).(OptionNone[A]); ok {
				var expr_625 []A
				expr_625 = out
				expr_627 = expr_625
			} else {
				panic("unreachable")
			}
		}
		expr_628 = expr_627
	}
	return expr_628
}
