// Code generated by mygo; DO NOT EDIT.

package compiler

import "os"
import "path/filepath"
import "strings"
import "github.com/mygo-lang/mygo/internal/mygo/typeinference2"
import . "github.com/mygo-lang/mygo/prelude"

type BootstrapGoModReplace struct {
	Module string
	Path   string
}
type BootstrapGoModRequire struct {
	Module  string
	Version string
}
type BootstrapGoPackageInfo struct {
	Funcs []typeinference2.GoFuncSignature
	Types []typeinference2.GoTypeSignature
}

func bootstrapGoImportDir(start string, importPath string) Option[string] {
	__mygo_expr_0 := bootstrapFindGoModuleRoot(start)
	var __mygo_expr_1 Option[string]
	if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
		__mygo_expr_1 = None[string]()
	} else {
		if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
			__mygo_expr_3 := bootstrapReadFileString(filepath.Join(__mygo_match___mygo_expr_2.F0, "go.mod"))
			var __mygo_expr_4 Option[string]
			if _, ok := __mygo_expr_3.(OptionNone[string]); ok {
				__mygo_expr_4 = None[string]()
			} else {
				if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(OptionSome[string]); ok {
					module := bootstrapGoModModulePath(__mygo_match___mygo_expr_5.F0)
					__mygo_expr_6 := bootstrapModuleImportDir(__mygo_match___mygo_expr_2.F0, module, importPath)
					var __mygo_expr_7 Option[string]
					if __mygo_match___mygo_expr_8, ok := __mygo_expr_6.(OptionSome[string]); ok {
						__mygo_expr_7 = Some[string](__mygo_match___mygo_expr_8.F0)
					} else {
						if _, ok := __mygo_expr_6.(OptionNone[string]); ok {
							__mygo_expr_7 = bootstrapGoImportDirReplaceEntry(__mygo_match___mygo_expr_2.F0, __mygo_match___mygo_expr_5.F0, importPath, 0)
						} else {
						}
					}
					__mygo_expr_4 = __mygo_expr_7
				} else {
				}
			}
			__mygo_expr_1 = __mygo_expr_4
		} else {
		}
	}
	return __mygo_expr_1
}
func bootstrapGoImportDirReplaceEntry(root string, content string, importPath string, index int) Option[string] {
	for {
		replaces := bootstrapGoModReplaceEntries(content)
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(replaces) {
			return bootstrapGoImportDirRequireEntry(content, importPath, 0)
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(replaces, index)
			var __mygo_expr_1 Option[string]
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[BootstrapGoModReplace]); ok {
				__mygo_expr_3 := bootstrapResolveReplaceRoot(root, __mygo_match___mygo_expr_2.F0.Path)
				var __mygo_expr_4 Option[string]
				if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(OptionSome[string]); ok {
					__mygo_expr_6 := bootstrapModuleImportDir(__mygo_match___mygo_expr_5.F0, __mygo_match___mygo_expr_2.F0.Module, importPath)
					var __mygo_expr_7 Option[string]
					if __mygo_match___mygo_expr_8, ok := __mygo_expr_6.(OptionSome[string]); ok {
						__mygo_expr_7 = Some[string](__mygo_match___mygo_expr_8.F0)
					} else {
						if _, ok := __mygo_expr_6.(OptionNone[string]); ok {
							__mygo_expr_7 = bootstrapGoImportDirReplaceEntry(root, content, importPath, index+1)
						} else {
						}
					}
					__mygo_expr_4 = __mygo_expr_7
				} else {
					if _, ok := __mygo_expr_3.(OptionNone[string]); ok {
						__mygo_expr_4 = bootstrapGoImportDirReplaceEntry(root, content, importPath, index+1)
					} else {
					}
				}
				__mygo_expr_1 = __mygo_expr_4
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[BootstrapGoModReplace]); ok {
					__mygo_expr_1 = bootstrapGoImportDirReplaceEntry(root, content, importPath, index+1)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapGoImportDirRequireEntry(content string, importPath string, index int) Option[string] {
	for {
		requires := bootstrapGoModRequireEntries(content)
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(requires) {
			return None[string]()
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(requires, index)
			var __mygo_expr_1 Option[string]
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[BootstrapGoModRequire]); ok {
				__mygo_expr_3 := bootstrapModuleImportSuffix(__mygo_match___mygo_expr_2.F0.Module, importPath)
				var __mygo_expr_4 Option[string]
				if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(OptionSome[string]); ok {
					__mygo_expr_4 = bootstrapGoImportDirCacheEntry(__mygo_match___mygo_expr_2.F0, __mygo_match___mygo_expr_5.F0, 0)
				} else {
					if _, ok := __mygo_expr_3.(OptionNone[string]); ok {
						__mygo_expr_4 = bootstrapGoImportDirRequireEntry(content, importPath, index+1)
					} else {
					}
				}
				__mygo_expr_1 = __mygo_expr_4
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[BootstrapGoModRequire]); ok {
					__mygo_expr_1 = bootstrapGoImportDirRequireEntry(content, importPath, index+1)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapGoImportDirCacheEntry(req BootstrapGoModRequire, suffix string, index int) Option[string] {
	for {
		cacheRoots := bootstrapGoModCacheRoots()
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(cacheRoots) {
			return None[string]()
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(cacheRoots, index)
			var __mygo_expr_1 Option[string]
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				modRoot := filepath.Join(__mygo_match___mygo_expr_2.F0, bootstrapModuleCachePath(req.Module, req.Version))
				__mygo_expr_3 := bootstrapExistingDir(filepath.Join(modRoot, filepath.FromSlash(suffix)))
				var __mygo_expr_4 Option[string]
				if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(OptionSome[string]); ok {
					__mygo_expr_4 = Some[string](__mygo_match___mygo_expr_5.F0)
				} else {
					if _, ok := __mygo_expr_3.(OptionNone[string]); ok {
						__mygo_expr_4 = bootstrapGoImportDirCacheEntry(req, suffix, index+1)
					} else {
					}
				}
				__mygo_expr_1 = __mygo_expr_4
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapGoImportDirCacheEntry(req, suffix, index+1)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapFindGoModuleRoot(start string) Option[string] {
	var __mygo_expr_2 Result[string, error]
	__mygo_expr_0, __mygo_expr_1 := filepath.Abs(start)
	if __mygo_expr_1 != nil {
		__mygo_expr_2 = Err[string, error](__mygo_expr_1)
	} else {
		__mygo_expr_2 = Ok[string, error](__mygo_expr_0)
	}
	__mygo_expr_3 := __mygo_expr_2
	var __mygo_expr_4 Option[string]
	if _, ok := __mygo_expr_3.(ResultErr[string, error]); ok {
		__mygo_expr_4 = None[string]()
	} else {
		if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(ResultOk[string, error]); ok {
			__mygo_expr_4 = bootstrapFindGoModuleRootUp(__mygo_match___mygo_expr_5.F0)
		} else {
		}
	}
	return __mygo_expr_4
}
func bootstrapFindGoModuleRootUp(cur string) Option[string] {
	for {
		var __mygo_expr_2 Result[os.FileInfo, error]
		__mygo_expr_0, __mygo_expr_1 := os.Stat(filepath.Join(cur, "go.mod"))
		if __mygo_expr_1 != nil {
			__mygo_expr_2 = Err[os.FileInfo, error](__mygo_expr_1)
		} else {
			__mygo_expr_2 = Ok[os.FileInfo, error](__mygo_expr_0)
		}
		__mygo_expr_3 := __mygo_expr_2
		var __mygo_expr_4 Option[string]
		if _, ok := __mygo_expr_3.(ResultOk[os.FileInfo, error]); ok {
			__mygo_expr_4 = Some[string](cur)
		} else {
			if _, ok := __mygo_expr_3.(ResultErr[os.FileInfo, error]); ok {
				parent := filepath.Dir(cur)
				var __mygo_expr_5 Option[string]
				if parent == cur {
					__mygo_expr_5 = None[string]()
				} else {
					__mygo_expr_5 = bootstrapFindGoModuleRootUp(parent)
				}
				__mygo_expr_4 = __mygo_expr_5
			} else {
			}
		}
		return __mygo_expr_4
	}
}
func bootstrapReadFileString(path string) Option[string] {
	var __mygo_expr_2 Result[[]byte, error]
	__mygo_expr_0, __mygo_expr_1 := os.ReadFile(path)
	if __mygo_expr_1 != nil {
		__mygo_expr_2 = Err[[]byte, error](__mygo_expr_1)
	} else {
		__mygo_expr_2 = Ok[[]byte, error](__mygo_expr_0)
	}
	__mygo_expr_3 := __mygo_expr_2
	var __mygo_expr_4 Option[string]
	if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(ResultOk[[]byte, error]); ok {
		__mygo_expr_4 = Some[string](string(__mygo_match___mygo_expr_5.F0))
	} else {
		if _, ok := __mygo_expr_3.(ResultErr[[]byte, error]); ok {
			__mygo_expr_4 = None[string]()
		} else {
		}
	}
	return __mygo_expr_4
}
func bootstrapGoModModulePath(content string) string {
	return bootstrapGoModModulePathIn(MygoIN6StringM5Split(content, "\n"), 0)
}
func bootstrapGoModModulePathIn(lines []string, index int) string {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(lines) {
			return ""
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(lines, index)
			var __mygo_expr_1 string
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				cleaned := bootstrapCleanGoModLine(__mygo_match___mygo_expr_2.F0)
				var __mygo_expr_3 string
				if MygoIN6StringM9HasPrefix(cleaned, "module ") {
					__mygo_expr_3 = MygoIN6StringM9TrimSpace(MygoIN6StringM10TrimPrefix(cleaned, "module "))
				} else {
					__mygo_expr_3 = bootstrapGoModModulePathIn(lines, index+1)
				}
				__mygo_expr_1 = __mygo_expr_3
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapGoModModulePathIn(lines, index+1)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapCleanGoModLine(line string) string {
	trimmed := MygoIN6StringM9TrimSpace(line)
	idx := MygoIN6StringM5Index(trimmed, "//")
	if idx >= 0 {
		__mygo_expr_0 := MygoIT10IIndexableFN15StringByteIndexGN6StringN3IntN4ByteEM5Slice(trimmed, 0, idx)
		var __mygo_expr_1 string
		if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
			__mygo_expr_1 = MygoIN6StringM9TrimSpace(__mygo_match___mygo_expr_2.F0)
		} else {
			if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
				__mygo_expr_1 = trimmed
			} else {
			}
		}
		return __mygo_expr_1
	} else {
		return trimmed
	}
}
func bootstrapGoModReplaceEntries(content string) []BootstrapGoModReplace {
	return bootstrapGoModReplaceEntriesIn(MygoIN6StringM5Split(content, "\n"), false, 0, []BootstrapGoModReplace{})
}
func bootstrapGoModReplaceEntriesIn(lines []string, inBlock bool, index int, out []BootstrapGoModReplace) []BootstrapGoModReplace {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(lines) {
			return out
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(lines, index)
			var __mygo_expr_1 []BootstrapGoModReplace
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				line := bootstrapCleanGoModLine(__mygo_match___mygo_expr_2.F0)
				var __mygo_expr_13 []BootstrapGoModReplace
				if line == "" {
					__mygo_expr_13 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, out)
				} else {
					var __mygo_expr_12 []BootstrapGoModReplace
					if line == "replace (" {
						__mygo_expr_12 = bootstrapGoModReplaceEntriesIn(lines, true, index+1, out)
					} else {
						var __mygo_expr_11 []BootstrapGoModReplace
						if inBlock && line == ")" {
							__mygo_expr_11 = bootstrapGoModReplaceEntriesIn(lines, false, index+1, out)
						} else {
							var __mygo_expr_10 []BootstrapGoModReplace
							if MygoIN6StringM9HasPrefix(line, "replace ") {
								entryLine := MygoIN6StringM9TrimSpace(MygoIN6StringM10TrimPrefix(line, "replace "))
								__mygo_expr_3 := bootstrapGoModReplaceFromFields(MygoIN6StringM6Fields(entryLine))
								var __mygo_expr_4 []BootstrapGoModReplace
								if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(OptionSome[BootstrapGoModReplace]); ok {
									__mygo_expr_4 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, MygoIN5SliceM6Append(out, __mygo_match___mygo_expr_5.F0))
								} else {
									if _, ok := __mygo_expr_3.(OptionNone[BootstrapGoModReplace]); ok {
										__mygo_expr_4 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, out)
									} else {
									}
								}
								__mygo_expr_10 = __mygo_expr_4
							} else {
								var __mygo_expr_9 []BootstrapGoModReplace
								if inBlock {
									__mygo_expr_6 := bootstrapGoModReplaceFromFields(MygoIN6StringM6Fields(line))
									var __mygo_expr_7 []BootstrapGoModReplace
									if __mygo_match___mygo_expr_8, ok := __mygo_expr_6.(OptionSome[BootstrapGoModReplace]); ok {
										__mygo_expr_7 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, MygoIN5SliceM6Append(out, __mygo_match___mygo_expr_8.F0))
									} else {
										if _, ok := __mygo_expr_6.(OptionNone[BootstrapGoModReplace]); ok {
											__mygo_expr_7 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, out)
										} else {
										}
									}
									__mygo_expr_9 = __mygo_expr_7
								} else {
									__mygo_expr_9 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, out)
								}
								__mygo_expr_10 = __mygo_expr_9
							}
							__mygo_expr_11 = __mygo_expr_10
						}
						__mygo_expr_12 = __mygo_expr_11
					}
					__mygo_expr_13 = __mygo_expr_12
				}
				__mygo_expr_1 = __mygo_expr_13
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapGoModReplaceEntriesIn(lines, inBlock, index+1, out)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapGoModReplaceFromFields(fields []string) Option[BootstrapGoModReplace] {
	return bootstrapGoModReplaceFromFieldsIn(fields, 0)
}
func bootstrapGoModReplaceFromFieldsIn(fields []string, index int) Option[BootstrapGoModReplace] {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(fields) {
			return None[BootstrapGoModReplace]()
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(fields, index)
			var __mygo_expr_1 Option[BootstrapGoModReplace]
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				var __mygo_expr_3 Option[BootstrapGoModReplace]
				if __mygo_match___mygo_expr_2.F0 == "=>" && index > 0 && index+1 < MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(fields) {
					__mygo_expr_3 = Some[BootstrapGoModReplace](BootstrapGoModReplace{Module: MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(fields, 0), ""), Path: MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(fields, index+1), "")})
				} else {
					__mygo_expr_3 = bootstrapGoModReplaceFromFieldsIn(fields, index+1)
				}
				__mygo_expr_1 = __mygo_expr_3
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = None[BootstrapGoModReplace]()
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapGoModRequireEntries(content string) []BootstrapGoModRequire {
	return bootstrapGoModRequireEntriesIn(MygoIN6StringM5Split(content, "\n"), false, 0, []BootstrapGoModRequire{})
}
func bootstrapGoModRequireEntriesIn(lines []string, inBlock bool, index int, out []BootstrapGoModRequire) []BootstrapGoModRequire {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(lines) {
			return out
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(lines, index)
			var __mygo_expr_1 []BootstrapGoModRequire
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				line := bootstrapCleanGoModLine(__mygo_match___mygo_expr_2.F0)
				var __mygo_expr_13 []BootstrapGoModRequire
				if line == "" {
					__mygo_expr_13 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, out)
				} else {
					var __mygo_expr_12 []BootstrapGoModRequire
					if line == "require (" {
						__mygo_expr_12 = bootstrapGoModRequireEntriesIn(lines, true, index+1, out)
					} else {
						var __mygo_expr_11 []BootstrapGoModRequire
						if inBlock && line == ")" {
							__mygo_expr_11 = bootstrapGoModRequireEntriesIn(lines, false, index+1, out)
						} else {
							var __mygo_expr_10 []BootstrapGoModRequire
							if MygoIN6StringM9HasPrefix(line, "require ") {
								entryLine := MygoIN6StringM9TrimSpace(MygoIN6StringM10TrimPrefix(line, "require "))
								__mygo_expr_3 := bootstrapGoModRequireFromFields(MygoIN6StringM6Fields(entryLine))
								var __mygo_expr_4 []BootstrapGoModRequire
								if __mygo_match___mygo_expr_5, ok := __mygo_expr_3.(OptionSome[BootstrapGoModRequire]); ok {
									__mygo_expr_4 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, MygoIN5SliceM6Append(out, __mygo_match___mygo_expr_5.F0))
								} else {
									if _, ok := __mygo_expr_3.(OptionNone[BootstrapGoModRequire]); ok {
										__mygo_expr_4 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, out)
									} else {
									}
								}
								__mygo_expr_10 = __mygo_expr_4
							} else {
								var __mygo_expr_9 []BootstrapGoModRequire
								if inBlock {
									__mygo_expr_6 := bootstrapGoModRequireFromFields(MygoIN6StringM6Fields(line))
									var __mygo_expr_7 []BootstrapGoModRequire
									if __mygo_match___mygo_expr_8, ok := __mygo_expr_6.(OptionSome[BootstrapGoModRequire]); ok {
										__mygo_expr_7 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, MygoIN5SliceM6Append(out, __mygo_match___mygo_expr_8.F0))
									} else {
										if _, ok := __mygo_expr_6.(OptionNone[BootstrapGoModRequire]); ok {
											__mygo_expr_7 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, out)
										} else {
										}
									}
									__mygo_expr_9 = __mygo_expr_7
								} else {
									__mygo_expr_9 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, out)
								}
								__mygo_expr_10 = __mygo_expr_9
							}
							__mygo_expr_11 = __mygo_expr_10
						}
						__mygo_expr_12 = __mygo_expr_11
					}
					__mygo_expr_13 = __mygo_expr_12
				}
				__mygo_expr_1 = __mygo_expr_13
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapGoModRequireEntriesIn(lines, inBlock, index+1, out)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapGoModRequireFromFields(fields []string) Option[BootstrapGoModRequire] {
	if MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(fields) >= 2 {
		return Some[BootstrapGoModRequire](BootstrapGoModRequire{Module: MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(fields, 0), ""), Version: MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(fields, 1), "")})
	} else {
		return None[BootstrapGoModRequire]()
	}
}
func bootstrapModuleImportDir(root string, module string, importPath string) Option[string] {
	if root == "" || module == "" {
		return None[string]()
	} else {
		__mygo_expr_0 := bootstrapModuleImportSuffix(module, importPath)
		var __mygo_expr_1 Option[string]
		if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
			__mygo_expr_1 = None[string]()
		} else {
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				__mygo_expr_1 = bootstrapExistingDir(filepath.Join(root, filepath.FromSlash(__mygo_match___mygo_expr_2.F0)))
			} else {
			}
		}
		return __mygo_expr_1
	}
}
func bootstrapModuleImportSuffix(module string, importPath string) Option[string] {
	if importPath == module {
		return Some[string]("")
	} else {
		prefix := module + "/"
		if MygoIN6StringM9HasPrefix(importPath, prefix) {
			return Some[string](MygoIN6StringM10TrimPrefix(importPath, prefix))
		} else {
			return None[string]()
		}
	}
}
func bootstrapResolveReplaceRoot(moduleRoot string, repl string) Option[string] {
	if repl == "" || MygoIN6StringM9HasPrefix(repl, ".") || filepath.IsAbs(repl) {
		var __mygo_expr_0 string
		if filepath.IsAbs(repl) {
			__mygo_expr_0 = repl
		} else {
			__mygo_expr_0 = filepath.Join(moduleRoot, repl)
		}
		resolved := __mygo_expr_0
		return Some[string](filepath.Clean(resolved))
	} else {
		return None[string]()
	}
}
func bootstrapExistingDir(path string) Option[string] {
	var __mygo_expr_2 Result[[]os.DirEntry, error]
	__mygo_expr_0, __mygo_expr_1 := os.ReadDir(path)
	if __mygo_expr_1 != nil {
		__mygo_expr_2 = Err[[]os.DirEntry, error](__mygo_expr_1)
	} else {
		__mygo_expr_2 = Ok[[]os.DirEntry, error](__mygo_expr_0)
	}
	__mygo_expr_3 := __mygo_expr_2
	var __mygo_expr_4 Option[string]
	if _, ok := __mygo_expr_3.(ResultOk[[]os.DirEntry, error]); ok {
		__mygo_expr_4 = Some[string](filepath.Clean(path))
	} else {
		if _, ok := __mygo_expr_3.(ResultErr[[]os.DirEntry, error]); ok {
			__mygo_expr_4 = None[string]()
		} else {
		}
	}
	return __mygo_expr_4
}
func bootstrapGoModCacheRoots() []string {
	gomodcache := os.Getenv("GOMODCACHE")
	var __mygo_expr_0 []string
	if gomodcache == "" {
		__mygo_expr_0 = []string{}
	} else {
		__mygo_expr_0 = []string{gomodcache}
	}
	fromEnv := __mygo_expr_0
	fromGopath := bootstrapGoModCacheRootsGopath(filepath.SplitList(os.Getenv("GOPATH")), 0, fromEnv)
	var __mygo_expr_3 Result[string, error]
	__mygo_expr_1, __mygo_expr_2 := os.UserHomeDir()
	if __mygo_expr_2 != nil {
		__mygo_expr_3 = Err[string, error](__mygo_expr_2)
	} else {
		__mygo_expr_3 = Ok[string, error](__mygo_expr_1)
	}
	__mygo_expr_4 := __mygo_expr_3
	var __mygo_expr_5 []string
	if __mygo_match___mygo_expr_6, ok := __mygo_expr_4.(ResultOk[string, error]); ok {
		var __mygo_expr_7 []string
		if __mygo_match___mygo_expr_6.F0 == "" {
			__mygo_expr_7 = fromGopath
		} else {
			__mygo_expr_7 = MygoIN5SliceM6Append(fromGopath, filepath.Join(__mygo_match___mygo_expr_6.F0, "go", "pkg", "mod"))
		}
		__mygo_expr_5 = __mygo_expr_7
	} else {
		if _, ok := __mygo_expr_4.(ResultErr[string, error]); ok {
			__mygo_expr_5 = fromGopath
		} else {
		}
	}
	withHome := __mygo_expr_5
	return bootstrapDedupeStrings(withHome, 0, []string{})
}
func bootstrapGoModCacheRootsGopath(parts []string, index int, acc []string) []string {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(parts) {
			return acc
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(parts, index)
			var __mygo_expr_1 []string
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				var __mygo_expr_3 []string
				if __mygo_match___mygo_expr_2.F0 == "" {
					__mygo_expr_3 = bootstrapGoModCacheRootsGopath(parts, index+1, acc)
				} else {
					__mygo_expr_3 = bootstrapGoModCacheRootsGopath(parts, index+1, MygoIN5SliceM6Append(acc, filepath.Join(__mygo_match___mygo_expr_2.F0, "pkg", "mod")))
				}
				__mygo_expr_1 = __mygo_expr_3
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapGoModCacheRootsGopath(parts, index+1, acc)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapDedupeStrings(items []string, index int, out []string) []string {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) {
			return out
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index)
			var __mygo_expr_1 []string
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				cleaned := filepath.Clean(__mygo_match___mygo_expr_2.F0)
				var __mygo_expr_3 []string
				if bootstrapContainsString(out, cleaned) {
					__mygo_expr_3 = bootstrapDedupeStrings(items, index+1, out)
				} else {
					__mygo_expr_3 = bootstrapDedupeStrings(items, index+1, MygoIN5SliceM6Append(out, cleaned))
				}
				__mygo_expr_1 = __mygo_expr_3
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapDedupeStrings(items, index+1, out)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapContainsString(items []string, value string) bool {
	return bootstrapContainsStringIn(items, value, 0)
}
func bootstrapContainsStringIn(items []string, value string, index int) bool {
	for {
		if index >= MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Len(items) {
			return false
		} else {
			__mygo_expr_0 := MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get(items, index)
			var __mygo_expr_1 bool
			if __mygo_match___mygo_expr_2, ok := __mygo_expr_0.(OptionSome[string]); ok {
				var __mygo_expr_3 bool
				if __mygo_match___mygo_expr_2.F0 == value {
					__mygo_expr_3 = true
				} else {
					__mygo_expr_3 = bootstrapContainsStringIn(items, value, index+1)
				}
				__mygo_expr_1 = __mygo_expr_3
			} else {
				if _, ok := __mygo_expr_0.(OptionNone[string]); ok {
					__mygo_expr_1 = bootstrapContainsStringIn(items, value, index+1)
				} else {
				}
			}
			return __mygo_expr_1
		}
	}
}
func bootstrapModuleCachePath(module string, version string) string {
	parts := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM3Map(MygoIN6StringM5Split(module, "/"), func(p string) string {
		return bootstrapEscapeModulePathElem(p)
	})
	return filepath.Join(strings.Join(parts, "/") + "@" + version)
}
func bootstrapEscapeModulePathElem(s string) string {
	rs := []rune(s)
	out := MygoIT11IEnumerableFN16SliceIEnumerableGN1TEGN5SliceGN1TEN1TEM4Fold(rs, []rune{}, func(acc []rune, r rune) []rune {
		ch := MygoIN6StringM9FromRunes([]rune{r})
		upper := MygoIN6StringM7ToUpper(ch)
		lower := MygoIN6StringM7ToLower(ch)
		if ch == upper && ch != lower {
			return MygoIN5SliceM6Append(MygoIN5SliceM6Append(acc, '!'), MygoIN6OptionM8UnwrapOr(MygoIT10IIndexableFN14SliceIndexableGN1TEGN5SliceGN1TEN3IntN1TEM3Get([]rune(lower), 0), r))
		} else {
			return MygoIN5SliceM6Append(acc, r)
		}
	})
	return MygoIN6StringM9FromRunes(out)
}
func bootstrapLoadGoPackage(workspaceRoot string, path string) Result[BootstrapGoPackageInfo, string] {
	return func() Result[BootstrapGoPackageInfo, string] {
		info, err := bootstrapLoadGoPackageGo(workspaceRoot, path)
		if err != nil {
			return Err[BootstrapGoPackageInfo, string](err.Error())
		}
		return Ok[BootstrapGoPackageInfo, string](info)
	}()
}
